/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.6.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCalendarWidget>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDateEdit>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QTimeEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QStackedWidget *stackedWidget;
    QWidget *page;
    QLabel *label;
    QLabel *label_2;
    QLineEdit *cuenta;
    QLineEdit *password;
    QLabel *label_3;
    QPushButton *pushButton;
    QWidget *page_2;
    QLabel *label_4;
    QLabel *label_5;
    QLineEdit *lineEdit_4;
    QLabel *label_6;
    QLabel *label_7;
    QLineEdit *lineEdit_5;
    QLineEdit *lineEdit_6;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;
    QWidget *page_3;
    QPushButton *pushButton_4;
    QPushButton *pushButton_5;
    QPushButton *pushButton_6;
    QPushButton *pushButton_7;
    QPushButton *pushButton_8;
    QPushButton *pushButton_9;
    QPushButton *pushButton_10;
    QPushButton *pushButton_11;
    QPushButton *pushButton_12;
    QLabel *label_8;
    QWidget *page_4;
    QLabel *label_9;
    QPushButton *pushButton_13;
    QPushButton *pushButton_14;
    QPushButton *pushButton_15;
    QPushButton *pushButton_79;
    QWidget *page_5;
    QLabel *label_10;
    QLabel *label_11;
    QLineEdit *NombreCrear;
    QLabel *label_12;
    QLineEdit *CrearCuenta;
    QLabel *label_13;
    QLineEdit *crearRol;
    QPushButton *pushButton_16;
    QPushButton *pushButton_17;
    QWidget *page_6;
    QPushButton *pushButton_18;
    QLabel *label_15;
    QLabel *label_16;
    QLineEdit *NombreEdit;
    QPushButton *pushButton_19;
    QLabel *label_17;
    QLineEdit *UsuarioEdit;
    QWidget *page_7;
    QLabel *label_18;
    QPushButton *pushButton_20;
    QPushButton *pushButton_21;
    QPushButton *pushButton_22;
    QPushButton *pushButton_23;
    QWidget *page_8;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QCalendarWidget *calendarWidget;
    QCalendarWidget *calendarWidget_2;
    QPushButton *pushButton_24;
    QPushButton *pushButton_25;
    QWidget *page_9;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QLineEdit *lineEdit_12;
    QLineEdit *lineEdit_13;
    QCalendarWidget *calendarWidget_3;
    QCalendarWidget *calendarWidget_4;
    QLabel *label_29;
    QLabel *label_30;
    QPushButton *pushButton_26;
    QPushButton *pushButton_27;
    QWidget *page_10;
    QLabel *label_31;
    QLabel *label_32;
    QLineEdit *lineEdit_14;
    QPushButton *pushButton_28;
    QLabel *label_33;
    QLineEdit *lineEdit_15;
    QPushButton *pushButton_29;
    QPushButton *pushButton_30;
    QWidget *page_11;
    QLabel *label_34;
    QPushButton *pushButton_31;
    QPushButton *pushButton_32;
    QPushButton *pushButton_33;
    QWidget *page_12;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *label_44;
    QLabel *label_45;
    QLabel *label_46;
    QPushButton *pushButton_34;
    QPushButton *pushButton_35;
    QLabel *label_47;
    QLineEdit *NamePacienteCrear;
    QLineEdit *IdentidadCrear;
    QLineEdit *Telefonocrear;
    QLineEdit *EmailCrear;
    QLineEdit *contacadiocionalCrear;
    QCalendarWidget *calendarFechaNacimiento;
    QLineEdit *TelefonoadiocionalCrear;
    QLineEdit *AlergiasCrear;
    QLineEdit *EnfermedadesCrear;
    QComboBox *TipodeSangreCrear;
    QLabel *label_14;
    QLineEdit *EncabezadoCrear;
    QLabel *label_102;
    QLineEdit *EmailadionalCrear;
    QWidget *page_13;
    QLabel *label_48;
    QLabel *label_49;
    QLabel *label_50;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_53;
    QLabel *label_54;
    QLineEdit *lineEdit_24;
    QLineEdit *lineEdit_25;
    QLineEdit *lineEdit_26;
    QLineEdit *lineEdit_27;
    QPushButton *pushButton_36;
    QPushButton *pushButton_37;
    QCalendarWidget *calendarWidget_5;
    QCalendarWidget *calendarWidget_7;
    QWidget *page_14;
    QLabel *label_55;
    QPushButton *pushButton_38;
    QPushButton *pushButton_39;
    QPushButton *pushButton_40;
    QWidget *page_15;
    QLabel *label_56;
    QLabel *label_57;
    QLabel *label_58;
    QLabel *label_59;
    QComboBox *comboBox_2;
    QComboBox *comboBox_3;
    QLabel *label_60;
    QPushButton *pushButton_41;
    QPushButton *pushButton_42;
    QWidget *page_16;
    QLabel *label_61;
    QRadioButton *radioButton;
    QRadioButton *radioButton_2;
    QCalendarWidget *calendarWidget_6;
    QComboBox *comboBox_4;
    QPushButton *pushButton_43;
    QPushButton *pushButton_44;
    QTextBrowser *textBrowser;
    QLabel *label_62;
    QWidget *page_17;
    QLabel *label_63;
    QPushButton *pushButton_45;
    QPushButton *pushButton_46;
    QPushButton *pushButton_47;
    QPushButton *pushButton_48;
    QWidget *page_18;
    QLabel *label_64;
    QLabel *label_65;
    QComboBox *comboBox_5;
    QLabel *label_66;
    QDateEdit *dateEdit_3;
    QLabel *label_67;
    QLabel *label_68;
    QTimeEdit *timeEdit;
    QTimeEdit *timeEdit_2;
    QLineEdit *lineEdit_28;
    QLabel *label_69;
    QLineEdit *lineEdit_29;
    QLabel *label_70;
    QPushButton *pushButton_49;
    QPushButton *pushButton_50;
    QWidget *page_19;
    QLabel *label_71;
    QLabel *label_72;
    QLineEdit *lineEdit_30;
    QLabel *label_73;
    QDateEdit *dateEdit_4;
    QLabel *label_74;
    QTimeEdit *timeEdit_3;
    QTimeEdit *timeEdit_4;
    QLabel *label_75;
    QLabel *label_76;
    QLineEdit *lineEdit_31;
    QPushButton *pushButton_51;
    QPushButton *pushButton_52;
    QWidget *page_20;
    QLabel *label_77;
    QLabel *label_78;
    QComboBox *comboBox_6;
    QPushButton *pushButton_53;
    QPushButton *pushButton_54;
    QWidget *page_21;
    QLabel *label_79;
    QPushButton *pushButton_55;
    QPushButton *pushButton_56;
    QPushButton *pushButton_57;
    QPushButton *pushButton_58;
    QPushButton *pushButton_59;
    QWidget *page_22;
    QLabel *label_80;
    QLabel *label_81;
    QLabel *label_82;
    QLabel *label_83;
    QLineEdit *lineEdit_32;
    QDateEdit *dateEdit_5;
    QTimeEdit *timeEdit_5;
    QPushButton *pushButton_60;
    QPushButton *pushButton_61;
    QWidget *page_23;
    QLabel *label_84;
    QLabel *label_85;
    QComboBox *comboBox_7;
    QLabel *label_86;
    QLabel *label_87;
    QDateEdit *dateEdit_6;
    QTimeEdit *timeEdit_6;
    QPushButton *pushButton_62;
    QPushButton *pushButton_63;
    QWidget *page_24;
    QLabel *label_88;
    QLabel *label_89;
    QPushButton *pushButton_64;
    QPushButton *pushButton_65;
    QComboBox *comboBox_8;
    QWidget *page_25;
    QLabel *label_90;
    QLabel *label_91;
    QPushButton *pushButton_66;
    QTextBrowser *textBrowser_2;
    QPushButton *pushButton_67;
    QDateEdit *dateEdit_7;
    QWidget *page_26;
    QLabel *label_92;
    QPushButton *pushButton_68;
    QPushButton *pushButton_69;
    QWidget *page_27;
    QLabel *label_93;
    QLabel *label_94;
    QLabel *label_95;
    QLabel *label_96;
    QPushButton *pushButton_70;
    QPushButton *pushButton_71;
    QLineEdit *lineEdit_33;
    QLineEdit *lineEdit_34;
    QWidget *page_28;
    QLabel *label_97;
    QPushButton *pushButton_72;
    QPushButton *pushButton_73;
    QPushButton *pushButton_78;
    QWidget *page_29;
    QLabel *label_98;
    QTextBrowser *textBrowser_3;
    QLabel *label_99;
    QDateEdit *dateEdit_8;
    QPushButton *pushButton_74;
    QPushButton *pushButton_75;
    QWidget *page_30;
    QLabel *label_100;
    QLabel *label_101;
    QDateEdit *dateEdit_9;
    QPushButton *pushButton_76;
    QTextBrowser *textBrowser_4;
    QPushButton *pushButton_77;
    QWidget *page_31;
    QLabel *label_103;
    QLabel *label_104;
    QLineEdit *otroRole;
    QPushButton *pushButton_80;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName("MainWindow");
        MainWindow->resize(800, 600);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName("centralwidget");
        stackedWidget = new QStackedWidget(centralwidget);
        stackedWidget->setObjectName("stackedWidget");
        stackedWidget->setGeometry(QRect(-20, 0, 801, 581));
        page = new QWidget();
        page->setObjectName("page");
        label = new QLabel(page);
        label->setObjectName("label");
        label->setGeometry(QRect(340, 0, 61, 31));
        QFont font;
        font.setFamilies({QString::fromUtf8("Segoe UI Black")});
        font.setPointSize(16);
        font.setBold(true);
        label->setFont(font);
        label_2 = new QLabel(page);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(300, 80, 131, 21));
        cuenta = new QLineEdit(page);
        cuenta->setObjectName("cuenta");
        cuenta->setGeometry(QRect(300, 100, 161, 31));
        password = new QLineEdit(page);
        password->setObjectName("password");
        password->setGeometry(QRect(300, 170, 161, 31));
        label_3 = new QLabel(page);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(300, 140, 141, 16));
        pushButton = new QPushButton(page);
        pushButton->setObjectName("pushButton");
        pushButton->setGeometry(QRect(330, 260, 111, 41));
        stackedWidget->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName("page_2");
        label_4 = new QLabel(page_2);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(360, 10, 91, 31));
        label_4->setFont(font);
        label_5 = new QLabel(page_2);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(370, 70, 49, 16));
        lineEdit_4 = new QLineEdit(page_2);
        lineEdit_4->setObjectName("lineEdit_4");
        lineEdit_4->setGeometry(QRect(340, 170, 131, 21));
        label_6 = new QLabel(page_2);
        label_6->setObjectName("label_6");
        label_6->setGeometry(QRect(380, 140, 49, 16));
        label_7 = new QLabel(page_2);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(380, 210, 49, 16));
        lineEdit_5 = new QLineEdit(page_2);
        lineEdit_5->setObjectName("lineEdit_5");
        lineEdit_5->setGeometry(QRect(340, 100, 131, 21));
        lineEdit_6 = new QLineEdit(page_2);
        lineEdit_6->setObjectName("lineEdit_6");
        lineEdit_6->setGeometry(QRect(340, 240, 131, 21));
        pushButton_2 = new QPushButton(page_2);
        pushButton_2->setObjectName("pushButton_2");
        pushButton_2->setGeometry(QRect(360, 290, 80, 24));
        pushButton_3 = new QPushButton(page_2);
        pushButton_3->setObjectName("pushButton_3");
        pushButton_3->setGeometry(QRect(40, 500, 80, 24));
        stackedWidget->addWidget(page_2);
        page_3 = new QWidget();
        page_3->setObjectName("page_3");
        pushButton_4 = new QPushButton(page_3);
        pushButton_4->setObjectName("pushButton_4");
        pushButton_4->setGeometry(QRect(270, 100, 191, 41));
        pushButton_5 = new QPushButton(page_3);
        pushButton_5->setObjectName("pushButton_5");
        pushButton_5->setGeometry(QRect(270, 150, 191, 41));
        pushButton_6 = new QPushButton(page_3);
        pushButton_6->setObjectName("pushButton_6");
        pushButton_6->setGeometry(QRect(270, 200, 191, 41));
        pushButton_7 = new QPushButton(page_3);
        pushButton_7->setObjectName("pushButton_7");
        pushButton_7->setGeometry(QRect(270, 250, 191, 41));
        pushButton_8 = new QPushButton(page_3);
        pushButton_8->setObjectName("pushButton_8");
        pushButton_8->setGeometry(QRect(270, 300, 191, 41));
        pushButton_9 = new QPushButton(page_3);
        pushButton_9->setObjectName("pushButton_9");
        pushButton_9->setGeometry(QRect(270, 350, 191, 41));
        pushButton_10 = new QPushButton(page_3);
        pushButton_10->setObjectName("pushButton_10");
        pushButton_10->setGeometry(QRect(270, 400, 191, 41));
        pushButton_11 = new QPushButton(page_3);
        pushButton_11->setObjectName("pushButton_11");
        pushButton_11->setGeometry(QRect(270, 450, 191, 41));
        pushButton_12 = new QPushButton(page_3);
        pushButton_12->setObjectName("pushButton_12");
        pushButton_12->setGeometry(QRect(60, 500, 80, 24));
        label_8 = new QLabel(page_3);
        label_8->setObjectName("label_8");
        label_8->setGeometry(QRect(270, 20, 181, 31));
        QFont font1;
        font1.setFamilies({QString::fromUtf8("Segoe UI Black")});
        font1.setPointSize(18);
        font1.setBold(true);
        label_8->setFont(font1);
        stackedWidget->addWidget(page_3);
        page_4 = new QWidget();
        page_4->setObjectName("page_4");
        label_9 = new QLabel(page_4);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(240, 10, 291, 41));
        label_9->setFont(font);
        pushButton_13 = new QPushButton(page_4);
        pushButton_13->setObjectName("pushButton_13");
        pushButton_13->setGeometry(QRect(290, 80, 191, 41));
        pushButton_14 = new QPushButton(page_4);
        pushButton_14->setObjectName("pushButton_14");
        pushButton_14->setGeometry(QRect(290, 150, 191, 41));
        pushButton_15 = new QPushButton(page_4);
        pushButton_15->setObjectName("pushButton_15");
        pushButton_15->setGeometry(QRect(300, 300, 191, 41));
        pushButton_79 = new QPushButton(page_4);
        pushButton_79->setObjectName("pushButton_79");
        pushButton_79->setGeometry(QRect(290, 220, 201, 41));
        stackedWidget->addWidget(page_4);
        page_5 = new QWidget();
        page_5->setObjectName("page_5");
        label_10 = new QLabel(page_5);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(290, 10, 211, 31));
        label_10->setFont(font);
        label_11 = new QLabel(page_5);
        label_11->setObjectName("label_11");
        label_11->setGeometry(QRect(40, 80, 49, 16));
        NombreCrear = new QLineEdit(page_5);
        NombreCrear->setObjectName("NombreCrear");
        NombreCrear->setGeometry(QRect(110, 80, 161, 21));
        label_12 = new QLabel(page_5);
        label_12->setObjectName("label_12");
        label_12->setGeometry(QRect(40, 130, 49, 16));
        CrearCuenta = new QLineEdit(page_5);
        CrearCuenta->setObjectName("CrearCuenta");
        CrearCuenta->setGeometry(QRect(110, 130, 161, 21));
        label_13 = new QLabel(page_5);
        label_13->setObjectName("label_13");
        label_13->setGeometry(QRect(40, 180, 49, 16));
        crearRol = new QLineEdit(page_5);
        crearRol->setObjectName("crearRol");
        crearRol->setGeometry(QRect(110, 180, 161, 21));
        pushButton_16 = new QPushButton(page_5);
        pushButton_16->setObjectName("pushButton_16");
        pushButton_16->setGeometry(QRect(360, 290, 121, 41));
        pushButton_17 = new QPushButton(page_5);
        pushButton_17->setObjectName("pushButton_17");
        pushButton_17->setGeometry(QRect(40, 490, 80, 24));
        stackedWidget->addWidget(page_5);
        page_6 = new QWidget();
        page_6->setObjectName("page_6");
        pushButton_18 = new QPushButton(page_6);
        pushButton_18->setObjectName("pushButton_18");
        pushButton_18->setGeometry(QRect(40, 510, 80, 24));
        label_15 = new QLabel(page_6);
        label_15->setObjectName("label_15");
        label_15->setGeometry(QRect(280, 10, 221, 31));
        label_15->setFont(font);
        label_16 = new QLabel(page_6);
        label_16->setObjectName("label_16");
        label_16->setGeometry(QRect(60, 100, 49, 16));
        NombreEdit = new QLineEdit(page_6);
        NombreEdit->setObjectName("NombreEdit");
        NombreEdit->setGeometry(QRect(150, 100, 161, 31));
        pushButton_19 = new QPushButton(page_6);
        pushButton_19->setObjectName("pushButton_19");
        pushButton_19->setGeometry(QRect(170, 210, 111, 31));
        label_17 = new QLabel(page_6);
        label_17->setObjectName("label_17");
        label_17->setGeometry(QRect(60, 170, 49, 16));
        UsuarioEdit = new QLineEdit(page_6);
        UsuarioEdit->setObjectName("UsuarioEdit");
        UsuarioEdit->setGeometry(QRect(150, 170, 161, 31));
        stackedWidget->addWidget(page_6);
        page_7 = new QWidget();
        page_7->setObjectName("page_7");
        label_18 = new QLabel(page_7);
        label_18->setObjectName("label_18");
        label_18->setGeometry(QRect(270, 20, 251, 31));
        label_18->setFont(font);
        pushButton_20 = new QPushButton(page_7);
        pushButton_20->setObjectName("pushButton_20");
        pushButton_20->setGeometry(QRect(290, 80, 191, 41));
        pushButton_21 = new QPushButton(page_7);
        pushButton_21->setObjectName("pushButton_21");
        pushButton_21->setGeometry(QRect(290, 140, 191, 41));
        pushButton_22 = new QPushButton(page_7);
        pushButton_22->setObjectName("pushButton_22");
        pushButton_22->setGeometry(QRect(290, 200, 191, 41));
        pushButton_23 = new QPushButton(page_7);
        pushButton_23->setObjectName("pushButton_23");
        pushButton_23->setGeometry(QRect(290, 270, 191, 41));
        stackedWidget->addWidget(page_7);
        page_8 = new QWidget();
        page_8->setObjectName("page_8");
        label_19 = new QLabel(page_8);
        label_19->setObjectName("label_19");
        label_19->setGeometry(QRect(320, 10, 181, 31));
        label_19->setFont(font);
        label_20 = new QLabel(page_8);
        label_20->setObjectName("label_20");
        label_20->setGeometry(QRect(60, 60, 49, 16));
        label_21 = new QLabel(page_8);
        label_21->setObjectName("label_21");
        label_21->setGeometry(QRect(300, 60, 71, 16));
        label_22 = new QLabel(page_8);
        label_22->setObjectName("label_22");
        label_22->setGeometry(QRect(550, 60, 71, 16));
        label_23 = new QLabel(page_8);
        label_23->setObjectName("label_23");
        label_23->setGeometry(QRect(60, 110, 91, 16));
        label_24 = new QLabel(page_8);
        label_24->setObjectName("label_24");
        label_24->setGeometry(QRect(550, 110, 121, 16));
        calendarWidget = new QCalendarWidget(page_8);
        calendarWidget->setObjectName("calendarWidget");
        calendarWidget->setGeometry(QRect(40, 140, 291, 211));
        calendarWidget_2 = new QCalendarWidget(page_8);
        calendarWidget_2->setObjectName("calendarWidget_2");
        calendarWidget_2->setGeometry(QRect(460, 140, 301, 201));
        pushButton_24 = new QPushButton(page_8);
        pushButton_24->setObjectName("pushButton_24");
        pushButton_24->setGeometry(QRect(350, 390, 80, 24));
        pushButton_25 = new QPushButton(page_8);
        pushButton_25->setObjectName("pushButton_25");
        pushButton_25->setGeometry(QRect(40, 510, 80, 24));
        stackedWidget->addWidget(page_8);
        page_9 = new QWidget();
        page_9->setObjectName("page_9");
        label_25 = new QLabel(page_9);
        label_25->setObjectName("label_25");
        label_25->setGeometry(QRect(340, 20, 151, 31));
        QFont font2;
        font2.setFamilies({QString::fromUtf8("Segoe UI Black")});
        font2.setPointSize(16);
        label_25->setFont(font2);
        label_26 = new QLabel(page_9);
        label_26->setObjectName("label_26");
        label_26->setGeometry(QRect(30, 70, 49, 16));
        label_27 = new QLabel(page_9);
        label_27->setObjectName("label_27");
        label_27->setGeometry(QRect(270, 70, 71, 16));
        label_28 = new QLabel(page_9);
        label_28->setObjectName("label_28");
        label_28->setGeometry(QRect(550, 70, 49, 16));
        lineEdit_12 = new QLineEdit(page_9);
        lineEdit_12->setObjectName("lineEdit_12");
        lineEdit_12->setGeometry(QRect(340, 70, 171, 31));
        lineEdit_13 = new QLineEdit(page_9);
        lineEdit_13->setObjectName("lineEdit_13");
        lineEdit_13->setGeometry(QRect(590, 70, 171, 31));
        calendarWidget_3 = new QCalendarWidget(page_9);
        calendarWidget_3->setObjectName("calendarWidget_3");
        calendarWidget_3->setGeometry(QRect(40, 230, 331, 221));
        calendarWidget_4 = new QCalendarWidget(page_9);
        calendarWidget_4->setObjectName("calendarWidget_4");
        calendarWidget_4->setGeometry(QRect(460, 230, 291, 221));
        label_29 = new QLabel(page_9);
        label_29->setObjectName("label_29");
        label_29->setGeometry(QRect(150, 190, 91, 16));
        label_30 = new QLabel(page_9);
        label_30->setObjectName("label_30");
        label_30->setGeometry(QRect(560, 190, 121, 16));
        pushButton_26 = new QPushButton(page_9);
        pushButton_26->setObjectName("pushButton_26");
        pushButton_26->setGeometry(QRect(360, 470, 80, 24));
        pushButton_27 = new QPushButton(page_9);
        pushButton_27->setObjectName("pushButton_27");
        pushButton_27->setGeometry(QRect(30, 520, 80, 24));
        stackedWidget->addWidget(page_9);
        page_10 = new QWidget();
        page_10->setObjectName("page_10");
        label_31 = new QLabel(page_10);
        label_31->setObjectName("label_31");
        label_31->setGeometry(QRect(310, 10, 141, 41));
        label_31->setFont(font2);
        label_32 = new QLabel(page_10);
        label_32->setObjectName("label_32");
        label_32->setGeometry(QRect(50, 70, 91, 16));
        lineEdit_14 = new QLineEdit(page_10);
        lineEdit_14->setObjectName("lineEdit_14");
        lineEdit_14->setGeometry(QRect(140, 70, 171, 21));
        pushButton_28 = new QPushButton(page_10);
        pushButton_28->setObjectName("pushButton_28");
        pushButton_28->setGeometry(QRect(470, 70, 80, 24));
        label_33 = new QLabel(page_10);
        label_33->setObjectName("label_33");
        label_33->setGeometry(QRect(50, 200, 49, 16));
        lineEdit_15 = new QLineEdit(page_10);
        lineEdit_15->setObjectName("lineEdit_15");
        lineEdit_15->setGeometry(QRect(100, 200, 171, 21));
        pushButton_29 = new QPushButton(page_10);
        pushButton_29->setObjectName("pushButton_29");
        pushButton_29->setGeometry(QRect(350, 270, 80, 24));
        pushButton_30 = new QPushButton(page_10);
        pushButton_30->setObjectName("pushButton_30");
        pushButton_30->setGeometry(QRect(40, 510, 80, 24));
        stackedWidget->addWidget(page_10);
        page_11 = new QWidget();
        page_11->setObjectName("page_11");
        label_34 = new QLabel(page_11);
        label_34->setObjectName("label_34");
        label_34->setGeometry(QRect(320, 10, 131, 41));
        label_34->setFont(font2);
        pushButton_31 = new QPushButton(page_11);
        pushButton_31->setObjectName("pushButton_31");
        pushButton_31->setGeometry(QRect(290, 70, 191, 41));
        pushButton_32 = new QPushButton(page_11);
        pushButton_32->setObjectName("pushButton_32");
        pushButton_32->setGeometry(QRect(290, 140, 191, 41));
        pushButton_33 = new QPushButton(page_11);
        pushButton_33->setObjectName("pushButton_33");
        pushButton_33->setGeometry(QRect(290, 210, 191, 41));
        stackedWidget->addWidget(page_11);
        page_12 = new QWidget();
        page_12->setObjectName("page_12");
        label_35 = new QLabel(page_12);
        label_35->setObjectName("label_35");
        label_35->setGeometry(QRect(290, 10, 191, 41));
        label_35->setFont(font2);
        label_36 = new QLabel(page_12);
        label_36->setObjectName("label_36");
        label_36->setGeometry(QRect(20, 90, 131, 16));
        label_37 = new QLabel(page_12);
        label_37->setObjectName("label_37");
        label_37->setGeometry(QRect(20, 120, 121, 16));
        label_38 = new QLabel(page_12);
        label_38->setObjectName("label_38");
        label_38->setGeometry(QRect(20, 60, 121, 16));
        label_39 = new QLabel(page_12);
        label_39->setObjectName("label_39");
        label_39->setGeometry(QRect(20, 150, 121, 16));
        label_40 = new QLabel(page_12);
        label_40->setObjectName("label_40");
        label_40->setGeometry(QRect(440, 90, 61, 16));
        label_41 = new QLabel(page_12);
        label_41->setObjectName("label_41");
        label_41->setGeometry(QRect(20, 360, 191, 16));
        label_42 = new QLabel(page_12);
        label_42->setObjectName("label_42");
        label_42->setGeometry(QRect(440, 130, 41, 16));
        label_43 = new QLabel(page_12);
        label_43->setObjectName("label_43");
        label_43->setGeometry(QRect(20, 390, 171, 16));
        label_44 = new QLabel(page_12);
        label_44->setObjectName("label_44");
        label_44->setGeometry(QRect(440, 180, 91, 16));
        label_45 = new QLabel(page_12);
        label_45->setObjectName("label_45");
        label_45->setGeometry(QRect(440, 220, 121, 21));
        label_46 = new QLabel(page_12);
        label_46->setObjectName("label_46");
        label_46->setGeometry(QRect(440, 270, 131, 16));
        pushButton_34 = new QPushButton(page_12);
        pushButton_34->setObjectName("pushButton_34");
        pushButton_34->setGeometry(QRect(360, 460, 80, 24));
        pushButton_35 = new QPushButton(page_12);
        pushButton_35->setObjectName("pushButton_35");
        pushButton_35->setGeometry(QRect(40, 520, 80, 24));
        label_47 = new QLabel(page_12);
        label_47->setObjectName("label_47");
        label_47->setGeometry(QRect(80, 60, 49, 16));
        NamePacienteCrear = new QLineEdit(page_12);
        NamePacienteCrear->setObjectName("NamePacienteCrear");
        NamePacienteCrear->setGeometry(QRect(150, 90, 171, 21));
        IdentidadCrear = new QLineEdit(page_12);
        IdentidadCrear->setObjectName("IdentidadCrear");
        IdentidadCrear->setGeometry(QRect(80, 120, 171, 21));
        Telefonocrear = new QLineEdit(page_12);
        Telefonocrear->setObjectName("Telefonocrear");
        Telefonocrear->setGeometry(QRect(510, 90, 171, 21));
        EmailCrear = new QLineEdit(page_12);
        EmailCrear->setObjectName("EmailCrear");
        EmailCrear->setGeometry(QRect(500, 130, 171, 21));
        contacadiocionalCrear = new QLineEdit(page_12);
        contacadiocionalCrear->setObjectName("contacadiocionalCrear");
        contacadiocionalCrear->setGeometry(QRect(210, 360, 171, 21));
        calendarFechaNacimiento = new QCalendarWidget(page_12);
        calendarFechaNacimiento->setObjectName("calendarFechaNacimiento");
        calendarFechaNacimiento->setGeometry(QRect(40, 170, 280, 163));
        TelefonoadiocionalCrear = new QLineEdit(page_12);
        TelefonoadiocionalCrear->setObjectName("TelefonoadiocionalCrear");
        TelefonoadiocionalCrear->setGeometry(QRect(200, 390, 171, 21));
        AlergiasCrear = new QLineEdit(page_12);
        AlergiasCrear->setObjectName("AlergiasCrear");
        AlergiasCrear->setGeometry(QRect(570, 220, 171, 21));
        EnfermedadesCrear = new QLineEdit(page_12);
        EnfermedadesCrear->setObjectName("EnfermedadesCrear");
        EnfermedadesCrear->setGeometry(QRect(560, 270, 171, 21));
        TipodeSangreCrear = new QComboBox(page_12);
        TipodeSangreCrear->addItem(QString());
        TipodeSangreCrear->addItem(QString());
        TipodeSangreCrear->addItem(QString());
        TipodeSangreCrear->addItem(QString());
        TipodeSangreCrear->addItem(QString());
        TipodeSangreCrear->addItem(QString());
        TipodeSangreCrear->addItem(QString());
        TipodeSangreCrear->addItem(QString());
        TipodeSangreCrear->addItem(QString());
        TipodeSangreCrear->setObjectName("TipodeSangreCrear");
        TipodeSangreCrear->setGeometry(QRect(540, 180, 141, 21));
        label_14 = new QLabel(page_12);
        label_14->setObjectName("label_14");
        label_14->setGeometry(QRect(440, 310, 91, 20));
        EncabezadoCrear = new QLineEdit(page_12);
        EncabezadoCrear->setObjectName("EncabezadoCrear");
        EncabezadoCrear->setGeometry(QRect(540, 310, 211, 21));
        label_102 = new QLabel(page_12);
        label_102->setObjectName("label_102");
        label_102->setGeometry(QRect(20, 420, 181, 16));
        EmailadionalCrear = new QLineEdit(page_12);
        EmailadionalCrear->setObjectName("EmailadionalCrear");
        EmailadionalCrear->setGeometry(QRect(200, 420, 171, 21));
        stackedWidget->addWidget(page_12);
        page_13 = new QWidget();
        page_13->setObjectName("page_13");
        label_48 = new QLabel(page_13);
        label_48->setObjectName("label_48");
        label_48->setGeometry(QRect(250, 10, 311, 41));
        label_48->setFont(font2);
        label_49 = new QLabel(page_13);
        label_49->setObjectName("label_49");
        label_49->setGeometry(QRect(460, 60, 49, 16));
        label_50 = new QLabel(page_13);
        label_50->setObjectName("label_50");
        label_50->setGeometry(QRect(40, 110, 141, 21));
        label_51 = new QLabel(page_13);
        label_51->setObjectName("label_51");
        label_51->setGeometry(QRect(40, 150, 91, 16));
        label_52 = new QLabel(page_13);
        label_52->setObjectName("label_52");
        label_52->setGeometry(QRect(40, 180, 111, 21));
        label_53 = new QLabel(page_13);
        label_53->setObjectName("label_53");
        label_53->setGeometry(QRect(40, 240, 161, 21));
        label_54 = new QLabel(page_13);
        label_54->setObjectName("label_54");
        label_54->setGeometry(QRect(40, 210, 151, 21));
        lineEdit_24 = new QLineEdit(page_13);
        lineEdit_24->setObjectName("lineEdit_24");
        lineEdit_24->setGeometry(QRect(180, 110, 211, 21));
        lineEdit_25 = new QLineEdit(page_13);
        lineEdit_25->setObjectName("lineEdit_25");
        lineEdit_25->setGeometry(QRect(130, 150, 211, 21));
        lineEdit_26 = new QLineEdit(page_13);
        lineEdit_26->setObjectName("lineEdit_26");
        lineEdit_26->setGeometry(QRect(150, 180, 211, 21));
        lineEdit_27 = new QLineEdit(page_13);
        lineEdit_27->setObjectName("lineEdit_27");
        lineEdit_27->setGeometry(QRect(210, 220, 211, 21));
        pushButton_36 = new QPushButton(page_13);
        pushButton_36->setObjectName("pushButton_36");
        pushButton_36->setGeometry(QRect(370, 460, 80, 24));
        pushButton_37 = new QPushButton(page_13);
        pushButton_37->setObjectName("pushButton_37");
        pushButton_37->setGeometry(QRect(50, 510, 80, 24));
        calendarWidget_5 = new QCalendarWidget(page_13);
        calendarWidget_5->setObjectName("calendarWidget_5");
        calendarWidget_5->setGeometry(QRect(513, 72, 301, 181));
        calendarWidget_7 = new QCalendarWidget(page_13);
        calendarWidget_7->setObjectName("calendarWidget_7");
        calendarWidget_7->setGeometry(QRect(40, 270, 304, 173));
        stackedWidget->addWidget(page_13);
        page_14 = new QWidget();
        page_14->setObjectName("page_14");
        label_55 = new QLabel(page_14);
        label_55->setObjectName("label_55");
        label_55->setGeometry(QRect(340, 10, 91, 31));
        label_55->setFont(font2);
        pushButton_38 = new QPushButton(page_14);
        pushButton_38->setObjectName("pushButton_38");
        pushButton_38->setGeometry(QRect(280, 60, 191, 41));
        pushButton_39 = new QPushButton(page_14);
        pushButton_39->setObjectName("pushButton_39");
        pushButton_39->setGeometry(QRect(280, 130, 191, 41));
        pushButton_40 = new QPushButton(page_14);
        pushButton_40->setObjectName("pushButton_40");
        pushButton_40->setGeometry(QRect(280, 200, 191, 41));
        stackedWidget->addWidget(page_14);
        page_15 = new QWidget();
        page_15->setObjectName("page_15");
        label_56 = new QLabel(page_15);
        label_56->setObjectName("label_56");
        label_56->setGeometry(QRect(320, 10, 151, 41));
        label_56->setFont(font2);
        label_57 = new QLabel(page_15);
        label_57->setObjectName("label_57");
        label_57->setGeometry(QRect(50, 70, 49, 16));
        label_58 = new QLabel(page_15);
        label_58->setObjectName("label_58");
        label_58->setGeometry(QRect(50, 130, 49, 16));
        label_59 = new QLabel(page_15);
        label_59->setObjectName("label_59");
        label_59->setGeometry(QRect(50, 200, 121, 21));
        comboBox_2 = new QComboBox(page_15);
        comboBox_2->setObjectName("comboBox_2");
        comboBox_2->setGeometry(QRect(100, 120, 181, 31));
        comboBox_3 = new QComboBox(page_15);
        comboBox_3->setObjectName("comboBox_3");
        comboBox_3->setGeometry(QRect(170, 200, 181, 31));
        label_60 = new QLabel(page_15);
        label_60->setObjectName("label_60");
        label_60->setGeometry(QRect(100, 70, 49, 16));
        pushButton_41 = new QPushButton(page_15);
        pushButton_41->setObjectName("pushButton_41");
        pushButton_41->setGeometry(QRect(30, 510, 80, 24));
        pushButton_42 = new QPushButton(page_15);
        pushButton_42->setObjectName("pushButton_42");
        pushButton_42->setGeometry(QRect(340, 310, 80, 24));
        stackedWidget->addWidget(page_15);
        page_16 = new QWidget();
        page_16->setObjectName("page_16");
        label_61 = new QLabel(page_16);
        label_61->setObjectName("label_61");
        label_61->setGeometry(QRect(300, 10, 151, 41));
        label_61->setFont(font2);
        radioButton = new QRadioButton(page_16);
        radioButton->setObjectName("radioButton");
        radioButton->setGeometry(QRect(50, 70, 91, 22));
        radioButton_2 = new QRadioButton(page_16);
        radioButton_2->setObjectName("radioButton_2");
        radioButton_2->setGeometry(QRect(500, 60, 91, 22));
        calendarWidget_6 = new QCalendarWidget(page_16);
        calendarWidget_6->setObjectName("calendarWidget_6");
        calendarWidget_6->setGeometry(QRect(480, 90, 281, 201));
        comboBox_4 = new QComboBox(page_16);
        comboBox_4->setObjectName("comboBox_4");
        comboBox_4->setGeometry(QRect(130, 70, 171, 21));
        pushButton_43 = new QPushButton(page_16);
        pushButton_43->setObjectName("pushButton_43");
        pushButton_43->setGeometry(QRect(340, 70, 80, 24));
        pushButton_44 = new QPushButton(page_16);
        pushButton_44->setObjectName("pushButton_44");
        pushButton_44->setGeometry(QRect(30, 500, 80, 24));
        textBrowser = new QTextBrowser(page_16);
        textBrowser->setObjectName("textBrowser");
        textBrowser->setGeometry(QRect(210, 200, 256, 192));
        label_62 = new QLabel(page_16);
        label_62->setObjectName("label_62");
        label_62->setGeometry(QRect(320, 180, 49, 16));
        stackedWidget->addWidget(page_16);
        page_17 = new QWidget();
        page_17->setObjectName("page_17");
        label_63 = new QLabel(page_17);
        label_63->setObjectName("label_63");
        label_63->setGeometry(QRect(310, 10, 151, 41));
        label_63->setFont(font2);
        pushButton_45 = new QPushButton(page_17);
        pushButton_45->setObjectName("pushButton_45");
        pushButton_45->setGeometry(QRect(290, 80, 191, 41));
        pushButton_46 = new QPushButton(page_17);
        pushButton_46->setObjectName("pushButton_46");
        pushButton_46->setGeometry(QRect(290, 140, 191, 41));
        pushButton_47 = new QPushButton(page_17);
        pushButton_47->setObjectName("pushButton_47");
        pushButton_47->setGeometry(QRect(290, 200, 191, 41));
        pushButton_48 = new QPushButton(page_17);
        pushButton_48->setObjectName("pushButton_48");
        pushButton_48->setGeometry(QRect(290, 260, 191, 41));
        stackedWidget->addWidget(page_17);
        page_18 = new QWidget();
        page_18->setObjectName("page_18");
        label_64 = new QLabel(page_18);
        label_64->setObjectName("label_64");
        label_64->setGeometry(QRect(300, 10, 201, 31));
        label_64->setFont(font2);
        label_65 = new QLabel(page_18);
        label_65->setObjectName("label_65");
        label_65->setGeometry(QRect(40, 70, 49, 16));
        comboBox_5 = new QComboBox(page_18);
        comboBox_5->setObjectName("comboBox_5");
        comboBox_5->setGeometry(QRect(110, 70, 131, 21));
        label_66 = new QLabel(page_18);
        label_66->setObjectName("label_66");
        label_66->setGeometry(QRect(40, 130, 121, 21));
        dateEdit_3 = new QDateEdit(page_18);
        dateEdit_3->setObjectName("dateEdit_3");
        dateEdit_3->setGeometry(QRect(100, 190, 110, 25));
        label_67 = new QLabel(page_18);
        label_67->setObjectName("label_67");
        label_67->setGeometry(QRect(40, 200, 49, 16));
        label_68 = new QLabel(page_18);
        label_68->setObjectName("label_68");
        label_68->setGeometry(QRect(40, 250, 91, 16));
        timeEdit = new QTimeEdit(page_18);
        timeEdit->setObjectName("timeEdit");
        timeEdit->setGeometry(QRect(130, 250, 118, 25));
        timeEdit_2 = new QTimeEdit(page_18);
        timeEdit_2->setObjectName("timeEdit_2");
        timeEdit_2->setGeometry(QRect(130, 300, 118, 25));
        lineEdit_28 = new QLineEdit(page_18);
        lineEdit_28->setObjectName("lineEdit_28");
        lineEdit_28->setGeometry(QRect(160, 130, 131, 21));
        label_69 = new QLabel(page_18);
        label_69->setObjectName("label_69");
        label_69->setGeometry(QRect(40, 300, 61, 16));
        lineEdit_29 = new QLineEdit(page_18);
        lineEdit_29->setObjectName("lineEdit_29");
        lineEdit_29->setGeometry(QRect(150, 360, 131, 21));
        label_70 = new QLabel(page_18);
        label_70->setObjectName("label_70");
        label_70->setGeometry(QRect(40, 360, 121, 21));
        pushButton_49 = new QPushButton(page_18);
        pushButton_49->setObjectName("pushButton_49");
        pushButton_49->setGeometry(QRect(350, 400, 80, 24));
        pushButton_50 = new QPushButton(page_18);
        pushButton_50->setObjectName("pushButton_50");
        pushButton_50->setGeometry(QRect(40, 480, 80, 24));
        stackedWidget->addWidget(page_18);
        page_19 = new QWidget();
        page_19->setObjectName("page_19");
        label_71 = new QLabel(page_19);
        label_71->setObjectName("label_71");
        label_71->setGeometry(QRect(280, 10, 241, 31));
        label_71->setFont(font2);
        label_72 = new QLabel(page_19);
        label_72->setObjectName("label_72");
        label_72->setGeometry(QRect(30, 70, 121, 21));
        lineEdit_30 = new QLineEdit(page_19);
        lineEdit_30->setObjectName("lineEdit_30");
        lineEdit_30->setGeometry(QRect(160, 70, 131, 21));
        label_73 = new QLabel(page_19);
        label_73->setObjectName("label_73");
        label_73->setGeometry(QRect(30, 120, 49, 16));
        dateEdit_4 = new QDateEdit(page_19);
        dateEdit_4->setObjectName("dateEdit_4");
        dateEdit_4->setGeometry(QRect(120, 120, 110, 25));
        label_74 = new QLabel(page_19);
        label_74->setObjectName("label_74");
        label_74->setGeometry(QRect(30, 180, 91, 16));
        timeEdit_3 = new QTimeEdit(page_19);
        timeEdit_3->setObjectName("timeEdit_3");
        timeEdit_3->setGeometry(QRect(150, 180, 118, 25));
        timeEdit_4 = new QTimeEdit(page_19);
        timeEdit_4->setObjectName("timeEdit_4");
        timeEdit_4->setGeometry(QRect(150, 230, 118, 25));
        label_75 = new QLabel(page_19);
        label_75->setObjectName("label_75");
        label_75->setGeometry(QRect(30, 240, 61, 16));
        label_76 = new QLabel(page_19);
        label_76->setObjectName("label_76");
        label_76->setGeometry(QRect(30, 290, 121, 21));
        lineEdit_31 = new QLineEdit(page_19);
        lineEdit_31->setObjectName("lineEdit_31");
        lineEdit_31->setGeometry(QRect(150, 290, 131, 21));
        pushButton_51 = new QPushButton(page_19);
        pushButton_51->setObjectName("pushButton_51");
        pushButton_51->setGeometry(QRect(370, 380, 80, 24));
        pushButton_52 = new QPushButton(page_19);
        pushButton_52->setObjectName("pushButton_52");
        pushButton_52->setGeometry(QRect(40, 500, 80, 24));
        stackedWidget->addWidget(page_19);
        page_20 = new QWidget();
        page_20->setObjectName("page_20");
        label_77 = new QLabel(page_20);
        label_77->setObjectName("label_77");
        label_77->setGeometry(QRect(290, 10, 221, 21));
        label_77->setFont(font2);
        label_78 = new QLabel(page_20);
        label_78->setObjectName("label_78");
        label_78->setGeometry(QRect(70, 100, 81, 16));
        comboBox_6 = new QComboBox(page_20);
        comboBox_6->setObjectName("comboBox_6");
        comboBox_6->setGeometry(QRect(170, 100, 161, 31));
        pushButton_53 = new QPushButton(page_20);
        pushButton_53->setObjectName("pushButton_53");
        pushButton_53->setGeometry(QRect(350, 280, 80, 24));
        pushButton_54 = new QPushButton(page_20);
        pushButton_54->setObjectName("pushButton_54");
        pushButton_54->setGeometry(QRect(90, 490, 80, 24));
        stackedWidget->addWidget(page_20);
        page_21 = new QWidget();
        page_21->setObjectName("page_21");
        label_79 = new QLabel(page_21);
        label_79->setObjectName("label_79");
        label_79->setGeometry(QRect(290, 10, 221, 41));
        label_79->setFont(font2);
        pushButton_55 = new QPushButton(page_21);
        pushButton_55->setObjectName("pushButton_55");
        pushButton_55->setGeometry(QRect(300, 70, 191, 41));
        pushButton_56 = new QPushButton(page_21);
        pushButton_56->setObjectName("pushButton_56");
        pushButton_56->setGeometry(QRect(300, 130, 191, 41));
        pushButton_57 = new QPushButton(page_21);
        pushButton_57->setObjectName("pushButton_57");
        pushButton_57->setGeometry(QRect(300, 190, 191, 41));
        pushButton_58 = new QPushButton(page_21);
        pushButton_58->setObjectName("pushButton_58");
        pushButton_58->setGeometry(QRect(300, 250, 191, 41));
        pushButton_59 = new QPushButton(page_21);
        pushButton_59->setObjectName("pushButton_59");
        pushButton_59->setGeometry(QRect(300, 310, 191, 41));
        stackedWidget->addWidget(page_21);
        page_22 = new QWidget();
        page_22->setObjectName("page_22");
        label_80 = new QLabel(page_22);
        label_80->setObjectName("label_80");
        label_80->setGeometry(QRect(350, 0, 121, 41));
        label_80->setFont(font2);
        label_81 = new QLabel(page_22);
        label_81->setObjectName("label_81");
        label_81->setGeometry(QRect(50, 60, 49, 16));
        label_82 = new QLabel(page_22);
        label_82->setObjectName("label_82");
        label_82->setGeometry(QRect(50, 110, 49, 16));
        label_83 = new QLabel(page_22);
        label_83->setObjectName("label_83");
        label_83->setGeometry(QRect(50, 160, 49, 16));
        lineEdit_32 = new QLineEdit(page_22);
        lineEdit_32->setObjectName("lineEdit_32");
        lineEdit_32->setGeometry(QRect(120, 60, 151, 21));
        dateEdit_5 = new QDateEdit(page_22);
        dateEdit_5->setObjectName("dateEdit_5");
        dateEdit_5->setGeometry(QRect(100, 110, 110, 25));
        timeEdit_5 = new QTimeEdit(page_22);
        timeEdit_5->setObjectName("timeEdit_5");
        timeEdit_5->setGeometry(QRect(100, 160, 118, 25));
        pushButton_60 = new QPushButton(page_22);
        pushButton_60->setObjectName("pushButton_60");
        pushButton_60->setGeometry(QRect(370, 240, 80, 24));
        pushButton_61 = new QPushButton(page_22);
        pushButton_61->setObjectName("pushButton_61");
        pushButton_61->setGeometry(QRect(40, 490, 81, 24));
        stackedWidget->addWidget(page_22);
        page_23 = new QWidget();
        page_23->setObjectName("page_23");
        label_84 = new QLabel(page_23);
        label_84->setObjectName("label_84");
        label_84->setGeometry(QRect(330, 10, 151, 41));
        label_84->setFont(font2);
        label_85 = new QLabel(page_23);
        label_85->setObjectName("label_85");
        label_85->setGeometry(QRect(70, 80, 49, 16));
        comboBox_7 = new QComboBox(page_23);
        comboBox_7->setObjectName("comboBox_7");
        comboBox_7->setGeometry(QRect(160, 80, 181, 31));
        label_86 = new QLabel(page_23);
        label_86->setObjectName("label_86");
        label_86->setGeometry(QRect(70, 200, 49, 16));
        label_87 = new QLabel(page_23);
        label_87->setObjectName("label_87");
        label_87->setGeometry(QRect(70, 140, 49, 16));
        dateEdit_6 = new QDateEdit(page_23);
        dateEdit_6->setObjectName("dateEdit_6");
        dateEdit_6->setGeometry(QRect(120, 140, 110, 25));
        timeEdit_6 = new QTimeEdit(page_23);
        timeEdit_6->setObjectName("timeEdit_6");
        timeEdit_6->setGeometry(QRect(130, 200, 118, 25));
        pushButton_62 = new QPushButton(page_23);
        pushButton_62->setObjectName("pushButton_62");
        pushButton_62->setGeometry(QRect(360, 350, 80, 24));
        pushButton_63 = new QPushButton(page_23);
        pushButton_63->setObjectName("pushButton_63");
        pushButton_63->setGeometry(QRect(100, 500, 80, 24));
        stackedWidget->addWidget(page_23);
        page_24 = new QWidget();
        page_24->setObjectName("page_24");
        label_88 = new QLabel(page_24);
        label_88->setObjectName("label_88");
        label_88->setGeometry(QRect(330, 10, 131, 41));
        label_88->setFont(font2);
        label_89 = new QLabel(page_24);
        label_89->setObjectName("label_89");
        label_89->setGeometry(QRect(70, 90, 49, 16));
        pushButton_64 = new QPushButton(page_24);
        pushButton_64->setObjectName("pushButton_64");
        pushButton_64->setGeometry(QRect(340, 330, 80, 24));
        pushButton_65 = new QPushButton(page_24);
        pushButton_65->setObjectName("pushButton_65");
        pushButton_65->setGeometry(QRect(50, 480, 80, 24));
        comboBox_8 = new QComboBox(page_24);
        comboBox_8->setObjectName("comboBox_8");
        comboBox_8->setGeometry(QRect(120, 90, 151, 31));
        stackedWidget->addWidget(page_24);
        page_25 = new QWidget();
        page_25->setObjectName("page_25");
        label_90 = new QLabel(page_25);
        label_90->setObjectName("label_90");
        label_90->setGeometry(QRect(340, 10, 151, 21));
        label_90->setFont(font2);
        label_91 = new QLabel(page_25);
        label_91->setObjectName("label_91");
        label_91->setGeometry(QRect(90, 80, 49, 16));
        pushButton_66 = new QPushButton(page_25);
        pushButton_66->setObjectName("pushButton_66");
        pushButton_66->setGeometry(QRect(430, 80, 80, 24));
        textBrowser_2 = new QTextBrowser(page_25);
        textBrowser_2->setObjectName("textBrowser_2");
        textBrowser_2->setGeometry(QRect(280, 140, 256, 192));
        pushButton_67 = new QPushButton(page_25);
        pushButton_67->setObjectName("pushButton_67");
        pushButton_67->setGeometry(QRect(100, 450, 80, 24));
        dateEdit_7 = new QDateEdit(page_25);
        dateEdit_7->setObjectName("dateEdit_7");
        dateEdit_7->setGeometry(QRect(140, 80, 110, 25));
        stackedWidget->addWidget(page_25);
        page_26 = new QWidget();
        page_26->setObjectName("page_26");
        label_92 = new QLabel(page_26);
        label_92->setObjectName("label_92");
        label_92->setGeometry(QRect(290, 10, 211, 31));
        label_92->setFont(font2);
        pushButton_68 = new QPushButton(page_26);
        pushButton_68->setObjectName("pushButton_68");
        pushButton_68->setGeometry(QRect(310, 80, 191, 41));
        pushButton_69 = new QPushButton(page_26);
        pushButton_69->setObjectName("pushButton_69");
        pushButton_69->setGeometry(QRect(310, 150, 191, 41));
        stackedWidget->addWidget(page_26);
        page_27 = new QWidget();
        page_27->setObjectName("page_27");
        label_93 = new QLabel(page_27);
        label_93->setObjectName("label_93");
        label_93->setGeometry(QRect(310, 10, 211, 41));
        label_93->setFont(font2);
        label_94 = new QLabel(page_27);
        label_94->setObjectName("label_94");
        label_94->setGeometry(QRect(60, 80, 111, 16));
        label_95 = new QLabel(page_27);
        label_95->setObjectName("label_95");
        label_95->setGeometry(QRect(60, 120, 49, 16));
        label_96 = new QLabel(page_27);
        label_96->setObjectName("label_96");
        label_96->setGeometry(QRect(60, 120, 101, 16));
        pushButton_70 = new QPushButton(page_27);
        pushButton_70->setObjectName("pushButton_70");
        pushButton_70->setGeometry(QRect(360, 230, 80, 24));
        pushButton_71 = new QPushButton(page_27);
        pushButton_71->setObjectName("pushButton_71");
        pushButton_71->setGeometry(QRect(60, 480, 80, 24));
        lineEdit_33 = new QLineEdit(page_27);
        lineEdit_33->setObjectName("lineEdit_33");
        lineEdit_33->setGeometry(QRect(170, 80, 191, 21));
        lineEdit_34 = new QLineEdit(page_27);
        lineEdit_34->setObjectName("lineEdit_34");
        lineEdit_34->setGeometry(QRect(170, 120, 191, 21));
        stackedWidget->addWidget(page_27);
        page_28 = new QWidget();
        page_28->setObjectName("page_28");
        label_97 = new QLabel(page_28);
        label_97->setObjectName("label_97");
        label_97->setGeometry(QRect(350, 10, 101, 31));
        label_97->setFont(font2);
        pushButton_72 = new QPushButton(page_28);
        pushButton_72->setObjectName("pushButton_72");
        pushButton_72->setGeometry(QRect(310, 80, 191, 41));
        pushButton_73 = new QPushButton(page_28);
        pushButton_73->setObjectName("pushButton_73");
        pushButton_73->setGeometry(QRect(310, 180, 191, 41));
        pushButton_78 = new QPushButton(page_28);
        pushButton_78->setObjectName("pushButton_78");
        pushButton_78->setGeometry(QRect(310, 260, 191, 41));
        stackedWidget->addWidget(page_28);
        page_29 = new QWidget();
        page_29->setObjectName("page_29");
        label_98 = new QLabel(page_29);
        label_98->setObjectName("label_98");
        label_98->setGeometry(QRect(340, 10, 101, 31));
        label_98->setFont(font2);
        textBrowser_3 = new QTextBrowser(page_29);
        textBrowser_3->setObjectName("textBrowser_3");
        textBrowser_3->setGeometry(QRect(290, 160, 256, 192));
        label_99 = new QLabel(page_29);
        label_99->setObjectName("label_99");
        label_99->setGeometry(QRect(60, 80, 49, 16));
        dateEdit_8 = new QDateEdit(page_29);
        dateEdit_8->setObjectName("dateEdit_8");
        dateEdit_8->setGeometry(QRect(130, 70, 110, 25));
        pushButton_74 = new QPushButton(page_29);
        pushButton_74->setObjectName("pushButton_74");
        pushButton_74->setGeometry(QRect(360, 120, 80, 24));
        pushButton_75 = new QPushButton(page_29);
        pushButton_75->setObjectName("pushButton_75");
        pushButton_75->setGeometry(QRect(60, 470, 80, 24));
        stackedWidget->addWidget(page_29);
        page_30 = new QWidget();
        page_30->setObjectName("page_30");
        label_100 = new QLabel(page_30);
        label_100->setObjectName("label_100");
        label_100->setGeometry(QRect(370, 10, 61, 31));
        label_100->setFont(font2);
        label_101 = new QLabel(page_30);
        label_101->setObjectName("label_101");
        label_101->setGeometry(QRect(60, 90, 49, 16));
        dateEdit_9 = new QDateEdit(page_30);
        dateEdit_9->setObjectName("dateEdit_9");
        dateEdit_9->setGeometry(QRect(110, 90, 110, 25));
        pushButton_76 = new QPushButton(page_30);
        pushButton_76->setObjectName("pushButton_76");
        pushButton_76->setGeometry(QRect(360, 160, 80, 24));
        textBrowser_4 = new QTextBrowser(page_30);
        textBrowser_4->setObjectName("textBrowser_4");
        textBrowser_4->setGeometry(QRect(290, 210, 271, 211));
        pushButton_77 = new QPushButton(page_30);
        pushButton_77->setObjectName("pushButton_77");
        pushButton_77->setGeometry(QRect(70, 480, 80, 24));
        stackedWidget->addWidget(page_30);
        page_31 = new QWidget();
        page_31->setObjectName("page_31");
        label_103 = new QLabel(page_31);
        label_103->setObjectName("label_103");
        label_103->setGeometry(QRect(350, 40, 201, 41));
        label_104 = new QLabel(page_31);
        label_104->setObjectName("label_104");
        label_104->setGeometry(QRect(250, 140, 131, 16));
        otroRole = new QLineEdit(page_31);
        otroRole->setObjectName("otroRole");
        otroRole->setGeometry(QRect(400, 140, 191, 21));
        pushButton_80 = new QPushButton(page_31);
        pushButton_80->setObjectName("pushButton_80");
        pushButton_80->setGeometry(QRect(340, 230, 111, 41));
        stackedWidget->addWidget(page_31);
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName("menubar");
        menubar->setGeometry(QRect(0, 0, 800, 24));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName("statusbar");
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        stackedWidget->setCurrentIndex(30);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "Login", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "Ingrese su cuenta:", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "Ingrese su password:", nullptr));
        pushButton->setText(QCoreApplication::translate("MainWindow", "Login", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindow", "Registro", nullptr));
        label_5->setText(QCoreApplication::translate("MainWindow", "Nombre:", nullptr));
        label_6->setText(QCoreApplication::translate("MainWindow", "Rol:", nullptr));
        label_7->setText(QCoreApplication::translate("MainWindow", "User:", nullptr));
        pushButton_2->setText(QCoreApplication::translate("MainWindow", "Crear", nullptr));
        pushButton_3->setText(QCoreApplication::translate("MainWindow", "Login", nullptr));
        pushButton_4->setText(QCoreApplication::translate("MainWindow", "Administraci\303\263n del Sistema", nullptr));
        pushButton_5->setText(QCoreApplication::translate("MainWindow", "Administraci\303\263n de Salas", nullptr));
        pushButton_6->setText(QCoreApplication::translate("MainWindow", "Expedientes", nullptr));
        pushButton_7->setText(QCoreApplication::translate("MainWindow", "Recetas", nullptr));
        pushButton_8->setText(QCoreApplication::translate("MainWindow", "Reservaciones", nullptr));
        pushButton_9->setText(QCoreApplication::translate("MainWindow", "Agente de Consultas", nullptr));
        pushButton_10->setText(QCoreApplication::translate("MainWindow", "Opciones de Usuario", nullptr));
        pushButton_11->setText(QCoreApplication::translate("MainWindow", "Reportes", nullptr));
        pushButton_12->setText(QCoreApplication::translate("MainWindow", "Salir", nullptr));
        label_8->setText(QCoreApplication::translate("MainWindow", "Men\303\272 Principal", nullptr));
        label_9->setText(QCoreApplication::translate("MainWindow", "Administraci\303\263n del Sistema", nullptr));
        pushButton_13->setText(QCoreApplication::translate("MainWindow", "Crear nuevo usuario", nullptr));
        pushButton_14->setText(QCoreApplication::translate("MainWindow", "Dar baja a un usuario", nullptr));
        pushButton_15->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        pushButton_79->setText(QCoreApplication::translate("MainWindow", "Agregar rol", nullptr));
        label_10->setText(QCoreApplication::translate("MainWindow", "Crear Nuevo Usuario", nullptr));
        label_11->setText(QCoreApplication::translate("MainWindow", "Nombre:", nullptr));
        label_12->setText(QCoreApplication::translate("MainWindow", "Cuenta:", nullptr));
        label_13->setText(QCoreApplication::translate("MainWindow", "Rol:", nullptr));
        pushButton_16->setText(QCoreApplication::translate("MainWindow", "Crear", nullptr));
        pushButton_17->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        pushButton_18->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_15->setText(QCoreApplication::translate("MainWindow", "Dar de baja a Usuario", nullptr));
        label_16->setText(QCoreApplication::translate("MainWindow", "Nombre:", nullptr));
        pushButton_19->setText(QCoreApplication::translate("MainWindow", "Dar de baja", nullptr));
        label_17->setText(QCoreApplication::translate("MainWindow", "Usuario:", nullptr));
        label_18->setText(QCoreApplication::translate("MainWindow", "Administraci\303\263n de Salas ", nullptr));
        pushButton_20->setText(QCoreApplication::translate("MainWindow", "Crear nueva sala", nullptr));
        pushButton_21->setText(QCoreApplication::translate("MainWindow", "Modificar sala", nullptr));
        pushButton_22->setText(QCoreApplication::translate("MainWindow", "Eliminar sala", nullptr));
        pushButton_23->setText(QCoreApplication::translate("MainWindow", "Regresar ", nullptr));
        label_19->setText(QCoreApplication::translate("MainWindow", "Crear Nueva Sala", nullptr));
        label_20->setText(QCoreApplication::translate("MainWindow", "C\303\263digo:", nullptr));
        label_21->setText(QCoreApplication::translate("MainWindow", "Descripci\303\263n:", nullptr));
        label_22->setText(QCoreApplication::translate("MainWindow", "Status:", nullptr));
        label_23->setText(QCoreApplication::translate("MainWindow", "Fecha de Inicio:", nullptr));
        label_24->setText(QCoreApplication::translate("MainWindow", "Fin de Disponibilidad:", nullptr));
        pushButton_24->setText(QCoreApplication::translate("MainWindow", "Crear", nullptr));
        pushButton_25->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_25->setText(QCoreApplication::translate("MainWindow", "Modificar Sala", nullptr));
        label_26->setText(QCoreApplication::translate("MainWindow", "Codigo:", nullptr));
        label_27->setText(QCoreApplication::translate("MainWindow", "Descripci\303\263n:", nullptr));
        label_28->setText(QCoreApplication::translate("MainWindow", "Status:", nullptr));
        label_29->setText(QCoreApplication::translate("MainWindow", "Fecha de Inicio:", nullptr));
        label_30->setText(QCoreApplication::translate("MainWindow", "Fin de Disponibilidad:", nullptr));
        pushButton_26->setText(QCoreApplication::translate("MainWindow", "Modificar", nullptr));
        pushButton_27->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_31->setText(QCoreApplication::translate("MainWindow", "Eliminar Sala", nullptr));
        label_32->setText(QCoreApplication::translate("MainWindow", "C\303\263digo de Sala:", nullptr));
        pushButton_28->setText(QCoreApplication::translate("MainWindow", "Buscar", nullptr));
        label_33->setText(QCoreApplication::translate("MainWindow", "Usuario:", nullptr));
        pushButton_29->setText(QCoreApplication::translate("MainWindow", "Eliminar", nullptr));
        pushButton_30->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_34->setText(QCoreApplication::translate("MainWindow", "Expedientes", nullptr));
        pushButton_31->setText(QCoreApplication::translate("MainWindow", "Nuevo Expediente", nullptr));
        pushButton_32->setText(QCoreApplication::translate("MainWindow", "Agregar Datos al Expediente", nullptr));
        pushButton_33->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_35->setText(QCoreApplication::translate("MainWindow", "Nuevo Expediente", nullptr));
        label_36->setText(QCoreApplication::translate("MainWindow", "Nombre del paciente:", nullptr));
        label_37->setText(QCoreApplication::translate("MainWindow", "Identidad:", nullptr));
        label_38->setText(QCoreApplication::translate("MainWindow", "C\303\263digo:", nullptr));
        label_39->setText(QCoreApplication::translate("MainWindow", "Fecha de nacimiento:", nullptr));
        label_40->setText(QCoreApplication::translate("MainWindow", "Telefono 1:", nullptr));
        label_41->setText(QCoreApplication::translate("MainWindow", "Nombre del contacto adicional:", nullptr));
        label_42->setText(QCoreApplication::translate("MainWindow", "Email:", nullptr));
        label_43->setText(QCoreApplication::translate("MainWindow", "Telefono contacto adicional:", nullptr));
        label_44->setText(QCoreApplication::translate("MainWindow", "Tipo de sangre:", nullptr));
        label_45->setText(QCoreApplication::translate("MainWindow", "Alegrias conocidas:", nullptr));
        label_46->setText(QCoreApplication::translate("MainWindow", "Enfermedades base:", nullptr));
        pushButton_34->setText(QCoreApplication::translate("MainWindow", "Crear ", nullptr));
        pushButton_35->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_47->setText(QCoreApplication::translate("MainWindow", "00", nullptr));
        TipodeSangreCrear->setItemText(0, QString());
        TipodeSangreCrear->setItemText(1, QCoreApplication::translate("MainWindow", "A+", nullptr));
        TipodeSangreCrear->setItemText(2, QCoreApplication::translate("MainWindow", "A-", nullptr));
        TipodeSangreCrear->setItemText(3, QCoreApplication::translate("MainWindow", "B+", nullptr));
        TipodeSangreCrear->setItemText(4, QCoreApplication::translate("MainWindow", "B-", nullptr));
        TipodeSangreCrear->setItemText(5, QCoreApplication::translate("MainWindow", "AB+", nullptr));
        TipodeSangreCrear->setItemText(6, QCoreApplication::translate("MainWindow", "AB-", nullptr));
        TipodeSangreCrear->setItemText(7, QCoreApplication::translate("MainWindow", "O+", nullptr));
        TipodeSangreCrear->setItemText(8, QCoreApplication::translate("MainWindow", "O-", nullptr));

        label_14->setText(QCoreApplication::translate("MainWindow", "Encabezado:", nullptr));
        label_102->setText(QCoreApplication::translate("MainWindow", "Email de contacto adicional:", nullptr));
        label_48->setText(QCoreApplication::translate("MainWindow", "Agregar Datos al Expediente", nullptr));
        label_49->setText(QCoreApplication::translate("MainWindow", "Fecha:", nullptr));
        label_50->setText(QCoreApplication::translate("MainWindow", "Sintomas presentados:", nullptr));
        label_51->setText(QCoreApplication::translate("MainWindow", "Observaciones:", nullptr));
        label_52->setText(QCoreApplication::translate("MainWindow", "Recomendaciones:", nullptr));
        label_53->setText(QCoreApplication::translate("MainWindow", "Proxima cita recomendada:", nullptr));
        label_54->setText(QCoreApplication::translate("MainWindow", "Comentarios adicionales:", nullptr));
        pushButton_36->setText(QCoreApplication::translate("MainWindow", "Agregar", nullptr));
        pushButton_37->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_55->setText(QCoreApplication::translate("MainWindow", "Recetas", nullptr));
        pushButton_38->setText(QCoreApplication::translate("MainWindow", "Nueva Receta", nullptr));
        pushButton_39->setText(QCoreApplication::translate("MainWindow", "Buscar Receta", nullptr));
        pushButton_40->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_56->setText(QCoreApplication::translate("MainWindow", "Nueva Receta", nullptr));
        label_57->setText(QCoreApplication::translate("MainWindow", "Fecha:", nullptr));
        label_58->setText(QCoreApplication::translate("MainWindow", "Paciente:", nullptr));
        label_59->setText(QCoreApplication::translate("MainWindow", "Medicamento y listas:", nullptr));
        label_60->setText(QCoreApplication::translate("MainWindow", "7/02/24", nullptr));
        pushButton_41->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        pushButton_42->setText(QCoreApplication::translate("MainWindow", "Crear", nullptr));
        label_61->setText(QCoreApplication::translate("MainWindow", "Buscar Receta", nullptr));
        radioButton->setText(QCoreApplication::translate("MainWindow", "Paciente", nullptr));
        radioButton_2->setText(QCoreApplication::translate("MainWindow", "Fecha", nullptr));
        pushButton_43->setText(QCoreApplication::translate("MainWindow", "Buscar", nullptr));
        pushButton_44->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_62->setText(QCoreApplication::translate("MainWindow", "Receta", nullptr));
        label_63->setText(QCoreApplication::translate("MainWindow", "Reservaciones", nullptr));
        pushButton_45->setText(QCoreApplication::translate("MainWindow", "Nueva Reservaci\303\263n", nullptr));
        pushButton_46->setText(QCoreApplication::translate("MainWindow", "Modificar Reservaci\303\263n", nullptr));
        pushButton_47->setText(QCoreApplication::translate("MainWindow", "Eliminar Reservaci\303\263n", nullptr));
        pushButton_48->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_64->setText(QCoreApplication::translate("MainWindow", "Nueva Reservaci\303\263n", nullptr));
        label_65->setText(QCoreApplication::translate("MainWindow", "Sala:", nullptr));
        label_66->setText(QCoreApplication::translate("MainWindow", "Nombre del paciente:", nullptr));
        label_67->setText(QCoreApplication::translate("MainWindow", "Fecha:", nullptr));
        label_68->setText(QCoreApplication::translate("MainWindow", "Hora de Inicio:", nullptr));
        label_69->setText(QCoreApplication::translate("MainWindow", "Hora final:", nullptr));
        label_70->setText(QCoreApplication::translate("MainWindow", "Nombre del doctor:", nullptr));
        pushButton_49->setText(QCoreApplication::translate("MainWindow", "Reservar", nullptr));
        pushButton_50->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_71->setText(QCoreApplication::translate("MainWindow", "Modificar Reservaci\303\263n", nullptr));
        label_72->setText(QCoreApplication::translate("MainWindow", "Nombre del paciente:", nullptr));
        label_73->setText(QCoreApplication::translate("MainWindow", "Fecha:", nullptr));
        label_74->setText(QCoreApplication::translate("MainWindow", "Hora de Inicio:", nullptr));
        label_75->setText(QCoreApplication::translate("MainWindow", "Hora final:", nullptr));
        label_76->setText(QCoreApplication::translate("MainWindow", "Nombre del doctor:", nullptr));
        pushButton_51->setText(QCoreApplication::translate("MainWindow", "Modificar", nullptr));
        pushButton_52->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_77->setText(QCoreApplication::translate("MainWindow", "Eliminar Reservaci\303\263n", nullptr));
        label_78->setText(QCoreApplication::translate("MainWindow", "Reservaciones:", nullptr));
        pushButton_53->setText(QCoreApplication::translate("MainWindow", "Eliminar", nullptr));
        pushButton_54->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_79->setText(QCoreApplication::translate("MainWindow", "Agenda de Consultas", nullptr));
        pushButton_55->setText(QCoreApplication::translate("MainWindow", "Nueva Cita", nullptr));
        pushButton_56->setText(QCoreApplication::translate("MainWindow", "Modificar Cita", nullptr));
        pushButton_57->setText(QCoreApplication::translate("MainWindow", "Eliminar Cita", nullptr));
        pushButton_58->setText(QCoreApplication::translate("MainWindow", "Consulta de Citas", nullptr));
        pushButton_59->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_80->setText(QCoreApplication::translate("MainWindow", "Nueva Cita", nullptr));
        label_81->setText(QCoreApplication::translate("MainWindow", "Nombre:", nullptr));
        label_82->setText(QCoreApplication::translate("MainWindow", "Fecha:", nullptr));
        label_83->setText(QCoreApplication::translate("MainWindow", "Hora:", nullptr));
        pushButton_60->setText(QCoreApplication::translate("MainWindow", "Crear", nullptr));
        pushButton_61->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_84->setText(QCoreApplication::translate("MainWindow", "Modificar Cita", nullptr));
        label_85->setText(QCoreApplication::translate("MainWindow", "Cita:", nullptr));
        label_86->setText(QCoreApplication::translate("MainWindow", "Hora:", nullptr));
        label_87->setText(QCoreApplication::translate("MainWindow", "Fecha:", nullptr));
        pushButton_62->setText(QCoreApplication::translate("MainWindow", "Modificar", nullptr));
        pushButton_63->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_88->setText(QCoreApplication::translate("MainWindow", "Eliminar Cita", nullptr));
        label_89->setText(QCoreApplication::translate("MainWindow", "Cita:", nullptr));
        pushButton_64->setText(QCoreApplication::translate("MainWindow", "Eliminar", nullptr));
        pushButton_65->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_90->setText(QCoreApplication::translate("MainWindow", "Consultar Cita", nullptr));
        label_91->setText(QCoreApplication::translate("MainWindow", "Fecha:", nullptr));
        pushButton_66->setText(QCoreApplication::translate("MainWindow", "Consultar", nullptr));
        pushButton_67->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_92->setText(QCoreApplication::translate("MainWindow", "Opciones de usuario", nullptr));
        pushButton_68->setText(QCoreApplication::translate("MainWindow", "Cambiar Contrase\303\261a", nullptr));
        pushButton_69->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_93->setText(QCoreApplication::translate("MainWindow", "Cambiar Contrase\303\261a", nullptr));
        label_94->setText(QCoreApplication::translate("MainWindow", "Contrase\303\261a Actual:", nullptr));
        label_95->setText(QString());
        label_96->setText(QCoreApplication::translate("MainWindow", "Nueva Contrase\303\261a:", nullptr));
        pushButton_70->setText(QCoreApplication::translate("MainWindow", "Cambiar", nullptr));
        pushButton_71->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_97->setText(QCoreApplication::translate("MainWindow", "Reportes", nullptr));
        pushButton_72->setText(QCoreApplication::translate("MainWindow", "Pacientes", nullptr));
        pushButton_73->setText(QCoreApplication::translate("MainWindow", "Citas", nullptr));
        pushButton_78->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_98->setText(QCoreApplication::translate("MainWindow", "Pacientes", nullptr));
        label_99->setText(QCoreApplication::translate("MainWindow", "Fecha:", nullptr));
        pushButton_74->setText(QCoreApplication::translate("MainWindow", "Ver", nullptr));
        pushButton_75->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_100->setText(QCoreApplication::translate("MainWindow", "Citas", nullptr));
        label_101->setText(QCoreApplication::translate("MainWindow", "Fecha:", nullptr));
        pushButton_76->setText(QCoreApplication::translate("MainWindow", "Ver", nullptr));
        pushButton_77->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_103->setText(QCoreApplication::translate("MainWindow", "Agregar rol", nullptr));
        label_104->setText(QCoreApplication::translate("MainWindow", "Ingrese el nuevo rol:", nullptr));
        pushButton_80->setText(QCoreApplication::translate("MainWindow", "Agregar", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
