/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.6.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCalendarWidget>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDateEdit>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QTimeEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QStackedWidget *stackedWidget;
    QWidget *Login;
    QLabel *label;
    QLabel *label_2;
    QLineEdit *cuenta;
    QLineEdit *password;
    QLabel *label_3;
    QPushButton *pushButton;
    QWidget *Registro;
    QLabel *label_4;
    QLabel *label_5;
    QLineEdit *lineEdit_4;
    QLabel *label_6;
    QLabel *label_7;
    QLineEdit *lineEdit_5;
    QLineEdit *lineEdit_6;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;
    QWidget *MenuPrincipal;
    QPushButton *pushButton_4;
    QPushButton *pushButton_5;
    QPushButton *pushButton_6;
    QPushButton *pushButton_7;
    QPushButton *pushButton_8;
    QPushButton *pushButton_9;
    QPushButton *pushButton_10;
    QPushButton *pushButton_11;
    QPushButton *pushButton_12;
    QLabel *label_8;
    QWidget *AdminitracionDeSistema;
    QLabel *label_9;
    QPushButton *pushButton_13;
    QPushButton *pushButton_14;
    QPushButton *pushButton_15;
    QPushButton *pushButton_79;
    QWidget *CrearUsuario;
    QLabel *label_10;
    QLabel *label_11;
    QLineEdit *NombreCrear;
    QLabel *label_12;
    QLineEdit *CrearCuenta;
    QLabel *label_13;
    QLineEdit *crearRol;
    QPushButton *pushButton_16;
    QPushButton *pushButton_17;
    QComboBox *RolUserCreate;
    QWidget *DarDeBajaUser;
    QPushButton *pushButton_18;
    QLabel *label_15;
    QLabel *label_16;
    QLineEdit *NombreEdit;
    QPushButton *pushButton_19;
    QLabel *label_17;
    QLineEdit *UsuarioEdit;
    QWidget *AdminitacionSalas;
    QLabel *label_18;
    QPushButton *pushButton_20;
    QPushButton *pushButton_21;
    QPushButton *pushButton_22;
    QPushButton *pushButton_23;
    QWidget *CrearNuevaSala;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QCalendarWidget *FechaStart;
    QCalendarWidget *FechaEnd;
    QPushButton *pushButton_24;
    QPushButton *pushButton_25;
    QLineEdit *DescripcionSala;
    QLabel *lbcodesala;
    QLabel *label_113;
    QTimeEdit *horafinal_crearSala;
    QLabel *label_114;
    QTimeEdit *horainicio_crearSala;
    QLabel *lb_status;
    QWidget *ModificarSala;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QLineEdit *DescripcioModificar;
    QCalendarWidget *fechaStarModi;
    QCalendarWidget *fechaFinalDisponibilidad;
    QLabel *label_29;
    QLabel *label_30;
    QPushButton *pushButton_26;
    QPushButton *pushButton_27;
    QLineEdit *CodeModificar;
    QLabel *label_115;
    QLabel *label_116;
    QTimeEdit *horainicio_modi;
    QTimeEdit *horafinal_modi;
    QPushButton *buscar_sala;
    QLineEdit *status_modi;
    QTextEdit *texto_sala;
    QWidget *EliminarSala_2;
    QLabel *label_31;
    QLabel *label_32;
    QLineEdit *codeDelete;
    QPushButton *pushButton_28;
    QLabel *label_33;
    QLineEdit *lineEdit_15;
    QPushButton *EliminarSala;
    QPushButton *pushButton_30;
    QWidget *Expedientes;
    QLabel *label_34;
    QPushButton *pushButton_31;
    QPushButton *pushButton_32;
    QPushButton *pushButton_33;
    QWidget *NuevoExpediente;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *label_44;
    QLabel *label_45;
    QLabel *label_46;
    QPushButton *pushButton_34;
    QPushButton *pushButton_35;
    QLabel *CodigoNextExpedienteLabel;
    QLineEdit *NamePacienteCrear;
    QLineEdit *IdentidadCrear;
    QLineEdit *Telefonocrear;
    QLineEdit *EmailCrear;
    QLineEdit *contacadiocionalCrear;
    QCalendarWidget *calendarFechaNacimiento;
    QLineEdit *TelefonoadiocionalCrear;
    QLineEdit *AlergiasCrear;
    QLineEdit *EnfermedadesCrear;
    QComboBox *TipodeSangreCrear;
    QLabel *label_14;
    QLineEdit *EncabezadoCrear;
    QLabel *label_102;
    QLineEdit *EmailadionalCrear;
    QWidget *AgregardataExp;
    QLabel *label_48;
    QLabel *label_49;
    QLabel *label_50;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_53;
    QLabel *label_54;
    QLineEdit *Sintomaspresen;
    QLineEdit *Observacionepaci;
    QLineEdit *RecomendacionesPaci;
    QLineEdit *AdicionalComents;
    QPushButton *pushButton_36;
    QPushButton *pushButton_37;
    QLabel *label_105;
    QLineEdit *NamePaciente;
    QLabel *label_106;
    QLineEdit *IdentidadPaciente;
    QLabel *label_107;
    QLineEdit *labelDiagnostico;
    QCalendarWidget *feachaDeCita;
    QCalendarWidget *ProximaCita;
    QWidget *Recetas;
    QLabel *label_55;
    QPushButton *pushButton_38;
    QPushButton *pushButton_39;
    QPushButton *pushButton_40;
    QWidget *NuevaReceta;
    QLabel *label_56;
    QLabel *label_57;
    QLabel *label_58;
    QLabel *label_59;
    QComboBox *paciente_cb;
    QComboBox *medicamento_cb;
    QLabel *lb_fecha_actual;
    QPushButton *pushButton_41;
    QPushButton *new_recipe;
    QLabel *label_60;
    QComboBox *dosis_cb;
    QWidget *BuscarReceta;
    QLabel *label_61;
    QRadioButton *radioButton;
    QRadioButton *radioButton_2;
    QCalendarWidget *calendarWidget_6;
    QComboBox *comboBox_4;
    QPushButton *pushButton_43;
    QPushButton *pushButton_44;
    QTextBrowser *textBrowser;
    QLabel *label_62;
    QWidget *Reservaciones;
    QLabel *label_63;
    QPushButton *pushButton_45;
    QPushButton *pushButton_46;
    QPushButton *pushButton_47;
    QPushButton *pushButton_48;
    QWidget *NuevaReservacion;
    QLabel *label_64;
    QLabel *label_65;
    QComboBox *salas_cb;
    QLabel *label_66;
    QDateEdit *date_reserva;
    QLabel *label_67;
    QLabel *label_68;
    QTimeEdit *Hora_inicio;
    QTimeEdit *Hora_final;
    QLineEdit *txt_name;
    QLabel *label_69;
    QLineEdit *txtnamedoctor;
    QLabel *label_70;
    QPushButton *bt_reservar;
    QPushButton *pushButton_50;
    QLineEdit *txtobservaciones;
    QLabel *label_108;
    QLabel *label_109;
    QLabel *lbcodereservas;
    QWidget *ModificarReserva;
    QLabel *label_71;
    QLabel *label_72;
    QLineEdit *txtnombreMR;
    QLabel *label_73;
    QDateEdit *FechaMR;
    QLabel *label_74;
    QTimeEdit *HoraIMR;
    QTimeEdit *HoraFMR;
    QLabel *label_75;
    QLabel *label_76;
    QLineEdit *nameDoctorMR;
    QPushButton *btmodificarR;
    QPushButton *pushButton_52;
    QLabel *label_110;
    QLineEdit *txtcodereserva;
    QLabel *label_111;
    QTextEdit *txtobeservacionesMR;
    QPushButton *bt_buscarMR;
    QWidget *EliminarReserva;
    QLabel *label_77;
    QLabel *label_78;
    QComboBox *comboBox_6;
    QPushButton *bt_EliminarR;
    QPushButton *pushButton_54;
    QLineEdit *txtcodeER;
    QLabel *label_112;
    QWidget *AgendaConsulta;
    QLabel *label_79;
    QPushButton *pushButton_55;
    QPushButton *pushButton_56;
    QPushButton *pushButton_57;
    QPushButton *pushButton_58;
    QPushButton *pushButton_59;
    QWidget *NuevaCita;
    QLabel *label_80;
    QLabel *label_81;
    QLabel *label_82;
    QLabel *label_83;
    QLineEdit *txtnombrecita;
    QDateEdit *dateCita;
    QTimeEdit *TimeCita;
    QPushButton *btNewCita;
    QPushButton *pushButton_61;
    QWidget *ModificarCita;
    QLabel *label_84;
    QLabel *label_85;
    QComboBox *comboBox_7;
    QLabel *label_86;
    QLabel *label_87;
    QDateEdit *dateEdit_6;
    QTimeEdit *timeEdit_6;
    QPushButton *pushButton_62;
    QPushButton *pushButton_63;
    QWidget *EliminarCita;
    QLabel *label_88;
    QLabel *label_89;
    QPushButton *pushButton_64;
    QPushButton *pushButton_65;
    QComboBox *comboBox_8;
    QWidget *ConsultarCita;
    QLabel *label_90;
    QLabel *label_91;
    QPushButton *pushButton_66;
    QTextBrowser *textBrowser_2;
    QPushButton *pushButton_67;
    QDateEdit *dateEdit_7;
    QWidget *OpcionesDeUsuario;
    QLabel *label_92;
    QPushButton *pushButton_68;
    QPushButton *pushButton_69;
    QWidget *CambiarPassword;
    QLabel *label_93;
    QLabel *label_94;
    QLabel *label_95;
    QLabel *label_96;
    QPushButton *pushButton_70;
    QPushButton *pushButton_71;
    QLineEdit *ActualPasswordUser;
    QLineEdit *NewPasswordUser;
    QLabel *label_47;
    QWidget *Reportes;
    QLabel *label_97;
    QPushButton *pushButton_72;
    QPushButton *pushButton_73;
    QPushButton *pushButton_78;
    QWidget *ReportePacientes;
    QLabel *label_98;
    QTextBrowser *textBrowser_3;
    QLabel *label_99;
    QDateEdit *dateEdit_8;
    QPushButton *pushButton_74;
    QPushButton *pushButton_75;
    QWidget *ReporteCitas;
    QLabel *label_100;
    QLabel *label_101;
    QDateEdit *dateEdit_9;
    QPushButton *pushButton_76;
    QTextBrowser *textBrowser_4;
    QPushButton *pushButton_77;
    QWidget *AgregarRoll;
    QLabel *label_103;
    QLabel *label_104;
    QLineEdit *otroRole;
    QPushButton *pushButton_80;
    QCheckBox *checkBox;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName("MainWindow");
        MainWindow->resize(875, 607);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName("centralwidget");
        stackedWidget = new QStackedWidget(centralwidget);
        stackedWidget->setObjectName("stackedWidget");
        stackedWidget->setGeometry(QRect(-20, 0, 891, 581));
        Login = new QWidget();
        Login->setObjectName("Login");
        label = new QLabel(Login);
        label->setObjectName("label");
        label->setGeometry(QRect(360, 0, 131, 61));
        QFont font;
        font.setFamilies({QString::fromUtf8("Segoe UI Black")});
        font.setPointSize(16);
        font.setBold(true);
        label->setFont(font);
        label_2 = new QLabel(Login);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(320, 80, 191, 31));
        label_2->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        cuenta = new QLineEdit(Login);
        cuenta->setObjectName("cuenta");
        cuenta->setGeometry(QRect(290, 110, 211, 31));
        password = new QLineEdit(Login);
        password->setObjectName("password");
        password->setGeometry(QRect(290, 180, 211, 31));
        label_3 = new QLabel(Login);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(310, 150, 181, 31));
        label_3->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        pushButton = new QPushButton(Login);
        pushButton->setObjectName("pushButton");
        pushButton->setGeometry(QRect(340, 230, 111, 41));
        pushButton->setStyleSheet(QString::fromUtf8("\n"
"font: 700 11pt \"Segoe UI\";"));
        stackedWidget->addWidget(Login);
        Registro = new QWidget();
        Registro->setObjectName("Registro");
        label_4 = new QLabel(Registro);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(360, 10, 141, 31));
        label_4->setFont(font);
        label_5 = new QLabel(Registro);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(370, 70, 91, 21));
        label_5->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        lineEdit_4 = new QLineEdit(Registro);
        lineEdit_4->setObjectName("lineEdit_4");
        lineEdit_4->setGeometry(QRect(320, 170, 181, 31));
        label_6 = new QLabel(Registro);
        label_6->setObjectName("label_6");
        label_6->setGeometry(QRect(380, 140, 49, 16));
        label_6->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        label_7 = new QLabel(Registro);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(380, 210, 49, 16));
        label_7->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        lineEdit_5 = new QLineEdit(Registro);
        lineEdit_5->setObjectName("lineEdit_5");
        lineEdit_5->setGeometry(QRect(320, 100, 181, 31));
        lineEdit_6 = new QLineEdit(Registro);
        lineEdit_6->setObjectName("lineEdit_6");
        lineEdit_6->setGeometry(QRect(320, 240, 181, 31));
        pushButton_2 = new QPushButton(Registro);
        pushButton_2->setObjectName("pushButton_2");
        pushButton_2->setGeometry(QRect(360, 290, 111, 41));
        pushButton_3 = new QPushButton(Registro);
        pushButton_3->setObjectName("pushButton_3");
        pushButton_3->setGeometry(QRect(40, 493, 101, 31));
        stackedWidget->addWidget(Registro);
        MenuPrincipal = new QWidget();
        MenuPrincipal->setObjectName("MenuPrincipal");
        pushButton_4 = new QPushButton(MenuPrincipal);
        pushButton_4->setObjectName("pushButton_4");
        pushButton_4->setGeometry(QRect(350, 100, 191, 41));
        pushButton_5 = new QPushButton(MenuPrincipal);
        pushButton_5->setObjectName("pushButton_5");
        pushButton_5->setGeometry(QRect(350, 150, 191, 41));
        pushButton_6 = new QPushButton(MenuPrincipal);
        pushButton_6->setObjectName("pushButton_6");
        pushButton_6->setGeometry(QRect(350, 200, 191, 41));
        pushButton_7 = new QPushButton(MenuPrincipal);
        pushButton_7->setObjectName("pushButton_7");
        pushButton_7->setGeometry(QRect(350, 250, 191, 41));
        pushButton_8 = new QPushButton(MenuPrincipal);
        pushButton_8->setObjectName("pushButton_8");
        pushButton_8->setGeometry(QRect(350, 300, 191, 41));
        pushButton_9 = new QPushButton(MenuPrincipal);
        pushButton_9->setObjectName("pushButton_9");
        pushButton_9->setGeometry(QRect(350, 350, 191, 41));
        pushButton_10 = new QPushButton(MenuPrincipal);
        pushButton_10->setObjectName("pushButton_10");
        pushButton_10->setGeometry(QRect(350, 400, 191, 41));
        pushButton_11 = new QPushButton(MenuPrincipal);
        pushButton_11->setObjectName("pushButton_11");
        pushButton_11->setGeometry(QRect(350, 450, 191, 41));
        pushButton_12 = new QPushButton(MenuPrincipal);
        pushButton_12->setObjectName("pushButton_12");
        pushButton_12->setGeometry(QRect(60, 500, 80, 24));
        label_8 = new QLabel(MenuPrincipal);
        label_8->setObjectName("label_8");
        label_8->setGeometry(QRect(330, 30, 241, 31));
        QFont font1;
        font1.setFamilies({QString::fromUtf8("Segoe UI Black")});
        font1.setPointSize(18);
        font1.setBold(true);
        label_8->setFont(font1);
        stackedWidget->addWidget(MenuPrincipal);
        AdminitracionDeSistema = new QWidget();
        AdminitracionDeSistema->setObjectName("AdminitracionDeSistema");
        label_9 = new QLabel(AdminitracionDeSistema);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(240, 10, 371, 41));
        label_9->setFont(font);
        pushButton_13 = new QPushButton(AdminitracionDeSistema);
        pushButton_13->setObjectName("pushButton_13");
        pushButton_13->setGeometry(QRect(290, 80, 191, 41));
        pushButton_14 = new QPushButton(AdminitracionDeSistema);
        pushButton_14->setObjectName("pushButton_14");
        pushButton_14->setGeometry(QRect(290, 150, 191, 41));
        pushButton_15 = new QPushButton(AdminitracionDeSistema);
        pushButton_15->setObjectName("pushButton_15");
        pushButton_15->setGeometry(QRect(300, 300, 191, 41));
        pushButton_79 = new QPushButton(AdminitracionDeSistema);
        pushButton_79->setObjectName("pushButton_79");
        pushButton_79->setGeometry(QRect(290, 220, 201, 41));
        stackedWidget->addWidget(AdminitracionDeSistema);
        CrearUsuario = new QWidget();
        CrearUsuario->setObjectName("CrearUsuario");
        label_10 = new QLabel(CrearUsuario);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(290, 10, 281, 31));
        label_10->setFont(font);
        label_11 = new QLabel(CrearUsuario);
        label_11->setObjectName("label_11");
        label_11->setGeometry(QRect(40, 80, 49, 16));
        NombreCrear = new QLineEdit(CrearUsuario);
        NombreCrear->setObjectName("NombreCrear");
        NombreCrear->setGeometry(QRect(110, 80, 161, 21));
        label_12 = new QLabel(CrearUsuario);
        label_12->setObjectName("label_12");
        label_12->setGeometry(QRect(40, 130, 49, 16));
        CrearCuenta = new QLineEdit(CrearUsuario);
        CrearCuenta->setObjectName("CrearCuenta");
        CrearCuenta->setGeometry(QRect(110, 130, 161, 21));
        label_13 = new QLabel(CrearUsuario);
        label_13->setObjectName("label_13");
        label_13->setGeometry(QRect(40, 180, 49, 16));
        crearRol = new QLineEdit(CrearUsuario);
        crearRol->setObjectName("crearRol");
        crearRol->setGeometry(QRect(100, 240, 161, 21));
        pushButton_16 = new QPushButton(CrearUsuario);
        pushButton_16->setObjectName("pushButton_16");
        pushButton_16->setGeometry(QRect(360, 290, 121, 41));
        pushButton_17 = new QPushButton(CrearUsuario);
        pushButton_17->setObjectName("pushButton_17");
        pushButton_17->setGeometry(QRect(40, 490, 80, 24));
        RolUserCreate = new QComboBox(CrearUsuario);
        RolUserCreate->setObjectName("RolUserCreate");
        RolUserCreate->setGeometry(QRect(100, 170, 181, 32));
        stackedWidget->addWidget(CrearUsuario);
        DarDeBajaUser = new QWidget();
        DarDeBajaUser->setObjectName("DarDeBajaUser");
        pushButton_18 = new QPushButton(DarDeBajaUser);
        pushButton_18->setObjectName("pushButton_18");
        pushButton_18->setGeometry(QRect(40, 510, 80, 24));
        label_15 = new QLabel(DarDeBajaUser);
        label_15->setObjectName("label_15");
        label_15->setGeometry(QRect(280, 10, 221, 31));
        label_15->setFont(font);
        label_16 = new QLabel(DarDeBajaUser);
        label_16->setObjectName("label_16");
        label_16->setGeometry(QRect(60, 100, 49, 16));
        NombreEdit = new QLineEdit(DarDeBajaUser);
        NombreEdit->setObjectName("NombreEdit");
        NombreEdit->setGeometry(QRect(150, 100, 161, 31));
        pushButton_19 = new QPushButton(DarDeBajaUser);
        pushButton_19->setObjectName("pushButton_19");
        pushButton_19->setGeometry(QRect(170, 210, 111, 31));
        label_17 = new QLabel(DarDeBajaUser);
        label_17->setObjectName("label_17");
        label_17->setGeometry(QRect(60, 170, 49, 16));
        UsuarioEdit = new QLineEdit(DarDeBajaUser);
        UsuarioEdit->setObjectName("UsuarioEdit");
        UsuarioEdit->setGeometry(QRect(150, 170, 161, 31));
        stackedWidget->addWidget(DarDeBajaUser);
        AdminitacionSalas = new QWidget();
        AdminitacionSalas->setObjectName("AdminitacionSalas");
        label_18 = new QLabel(AdminitacionSalas);
        label_18->setObjectName("label_18");
        label_18->setGeometry(QRect(220, 20, 321, 31));
        label_18->setFont(font);
        pushButton_20 = new QPushButton(AdminitacionSalas);
        pushButton_20->setObjectName("pushButton_20");
        pushButton_20->setGeometry(QRect(290, 80, 191, 41));
        pushButton_21 = new QPushButton(AdminitacionSalas);
        pushButton_21->setObjectName("pushButton_21");
        pushButton_21->setGeometry(QRect(290, 140, 191, 41));
        pushButton_22 = new QPushButton(AdminitacionSalas);
        pushButton_22->setObjectName("pushButton_22");
        pushButton_22->setGeometry(QRect(290, 200, 191, 41));
        pushButton_23 = new QPushButton(AdminitacionSalas);
        pushButton_23->setObjectName("pushButton_23");
        pushButton_23->setGeometry(QRect(290, 270, 191, 41));
        stackedWidget->addWidget(AdminitacionSalas);
        CrearNuevaSala = new QWidget();
        CrearNuevaSala->setObjectName("CrearNuevaSala");
        label_19 = new QLabel(CrearNuevaSala);
        label_19->setObjectName("label_19");
        label_19->setGeometry(QRect(280, 10, 241, 31));
        label_19->setFont(font);
        label_20 = new QLabel(CrearNuevaSala);
        label_20->setObjectName("label_20");
        label_20->setGeometry(QRect(60, 60, 49, 16));
        label_21 = new QLabel(CrearNuevaSala);
        label_21->setObjectName("label_21");
        label_21->setGeometry(QRect(300, 60, 71, 16));
        label_22 = new QLabel(CrearNuevaSala);
        label_22->setObjectName("label_22");
        label_22->setGeometry(QRect(550, 60, 71, 16));
        label_23 = new QLabel(CrearNuevaSala);
        label_23->setObjectName("label_23");
        label_23->setGeometry(QRect(40, 130, 91, 16));
        label_24 = new QLabel(CrearNuevaSala);
        label_24->setObjectName("label_24");
        label_24->setGeometry(QRect(480, 130, 121, 16));
        FechaStart = new QCalendarWidget(CrearNuevaSala);
        FechaStart->setObjectName("FechaStart");
        FechaStart->setGeometry(QRect(40, 160, 291, 211));
        FechaEnd = new QCalendarWidget(CrearNuevaSala);
        FechaEnd->setObjectName("FechaEnd");
        FechaEnd->setGeometry(QRect(480, 160, 301, 201));
        pushButton_24 = new QPushButton(CrearNuevaSala);
        pushButton_24->setObjectName("pushButton_24");
        pushButton_24->setGeometry(QRect(400, 460, 80, 24));
        pushButton_25 = new QPushButton(CrearNuevaSala);
        pushButton_25->setObjectName("pushButton_25");
        pushButton_25->setGeometry(QRect(40, 510, 80, 24));
        DescripcionSala = new QLineEdit(CrearNuevaSala);
        DescripcionSala->setObjectName("DescripcionSala");
        DescripcionSala->setGeometry(QRect(380, 60, 113, 21));
        lbcodesala = new QLabel(CrearNuevaSala);
        lbcodesala->setObjectName("lbcodesala");
        lbcodesala->setGeometry(QRect(110, 60, 63, 20));
        label_113 = new QLabel(CrearNuevaSala);
        label_113->setObjectName("label_113");
        label_113->setGeometry(QRect(50, 390, 131, 16));
        horafinal_crearSala = new QTimeEdit(CrearNuevaSala);
        horafinal_crearSala->setObjectName("horafinal_crearSala");
        horafinal_crearSala->setGeometry(QRect(660, 390, 118, 25));
        label_114 = new QLabel(CrearNuevaSala);
        label_114->setObjectName("label_114");
        label_114->setGeometry(QRect(490, 390, 161, 21));
        horainicio_crearSala = new QTimeEdit(CrearNuevaSala);
        horainicio_crearSala->setObjectName("horainicio_crearSala");
        horainicio_crearSala->setGeometry(QRect(180, 390, 118, 25));
        lb_status = new QLabel(CrearNuevaSala);
        lb_status->setObjectName("lb_status");
        lb_status->setGeometry(QRect(590, 60, 101, 16));
        stackedWidget->addWidget(CrearNuevaSala);
        ModificarSala = new QWidget();
        ModificarSala->setObjectName("ModificarSala");
        label_25 = new QLabel(ModificarSala);
        label_25->setObjectName("label_25");
        label_25->setGeometry(QRect(300, 10, 201, 31));
        QFont font2;
        font2.setFamilies({QString::fromUtf8("Segoe UI Black")});
        font2.setPointSize(16);
        label_25->setFont(font2);
        label_26 = new QLabel(ModificarSala);
        label_26->setObjectName("label_26");
        label_26->setGeometry(QRect(30, 70, 49, 16));
        label_27 = new QLabel(ModificarSala);
        label_27->setObjectName("label_27");
        label_27->setGeometry(QRect(270, 70, 81, 16));
        label_28 = new QLabel(ModificarSala);
        label_28->setObjectName("label_28");
        label_28->setGeometry(QRect(550, 70, 49, 16));
        DescripcioModificar = new QLineEdit(ModificarSala);
        DescripcioModificar->setObjectName("DescripcioModificar");
        DescripcioModificar->setGeometry(QRect(350, 70, 171, 31));
        fechaStarModi = new QCalendarWidget(ModificarSala);
        fechaStarModi->setObjectName("fechaStarModi");
        fechaStarModi->setGeometry(QRect(40, 310, 271, 171));
        fechaFinalDisponibilidad = new QCalendarWidget(ModificarSala);
        fechaFinalDisponibilidad->setObjectName("fechaFinalDisponibilidad");
        fechaFinalDisponibilidad->setGeometry(QRect(500, 180, 291, 221));
        label_29 = new QLabel(ModificarSala);
        label_29->setObjectName("label_29");
        label_29->setGeometry(QRect(60, 280, 91, 16));
        label_30 = new QLabel(ModificarSala);
        label_30->setObjectName("label_30");
        label_30->setGeometry(QRect(560, 150, 121, 16));
        pushButton_26 = new QPushButton(ModificarSala);
        pushButton_26->setObjectName("pushButton_26");
        pushButton_26->setGeometry(QRect(410, 490, 80, 24));
        pushButton_27 = new QPushButton(ModificarSala);
        pushButton_27->setObjectName("pushButton_27");
        pushButton_27->setGeometry(QRect(40, 530, 80, 24));
        CodeModificar = new QLineEdit(ModificarSala);
        CodeModificar->setObjectName("CodeModificar");
        CodeModificar->setGeometry(QRect(80, 70, 113, 21));
        label_115 = new QLabel(ModificarSala);
        label_115->setObjectName("label_115");
        label_115->setGeometry(QRect(50, 490, 131, 16));
        label_116 = new QLabel(ModificarSala);
        label_116->setObjectName("label_116");
        label_116->setGeometry(QRect(500, 420, 171, 21));
        horainicio_modi = new QTimeEdit(ModificarSala);
        horainicio_modi->setObjectName("horainicio_modi");
        horainicio_modi->setGeometry(QRect(190, 490, 118, 25));
        horafinal_modi = new QTimeEdit(ModificarSala);
        horafinal_modi->setObjectName("horafinal_modi");
        horafinal_modi->setGeometry(QRect(680, 420, 118, 25));
        buscar_sala = new QPushButton(ModificarSala);
        buscar_sala->setObjectName("buscar_sala");
        buscar_sala->setGeometry(QRect(100, 110, 80, 24));
        status_modi = new QLineEdit(ModificarSala);
        status_modi->setObjectName("status_modi");
        status_modi->setGeometry(QRect(600, 70, 113, 24));
        texto_sala = new QTextEdit(ModificarSala);
        texto_sala->setObjectName("texto_sala");
        texto_sala->setGeometry(QRect(40, 150, 241, 121));
        stackedWidget->addWidget(ModificarSala);
        EliminarSala_2 = new QWidget();
        EliminarSala_2->setObjectName("EliminarSala_2");
        label_31 = new QLabel(EliminarSala_2);
        label_31->setObjectName("label_31");
        label_31->setGeometry(QRect(310, 10, 201, 41));
        label_31->setFont(font2);
        label_32 = new QLabel(EliminarSala_2);
        label_32->setObjectName("label_32");
        label_32->setGeometry(QRect(50, 70, 91, 16));
        codeDelete = new QLineEdit(EliminarSala_2);
        codeDelete->setObjectName("codeDelete");
        codeDelete->setGeometry(QRect(140, 70, 171, 21));
        pushButton_28 = new QPushButton(EliminarSala_2);
        pushButton_28->setObjectName("pushButton_28");
        pushButton_28->setGeometry(QRect(720, 450, 80, 24));
        label_33 = new QLabel(EliminarSala_2);
        label_33->setObjectName("label_33");
        label_33->setGeometry(QRect(50, 200, 49, 16));
        lineEdit_15 = new QLineEdit(EliminarSala_2);
        lineEdit_15->setObjectName("lineEdit_15");
        lineEdit_15->setGeometry(QRect(100, 200, 171, 21));
        EliminarSala = new QPushButton(EliminarSala_2);
        EliminarSala->setObjectName("EliminarSala");
        EliminarSala->setGeometry(QRect(350, 270, 80, 24));
        pushButton_30 = new QPushButton(EliminarSala_2);
        pushButton_30->setObjectName("pushButton_30");
        pushButton_30->setGeometry(QRect(40, 510, 80, 24));
        stackedWidget->addWidget(EliminarSala_2);
        Expedientes = new QWidget();
        Expedientes->setObjectName("Expedientes");
        label_34 = new QLabel(Expedientes);
        label_34->setObjectName("label_34");
        label_34->setGeometry(QRect(320, 10, 231, 41));
        label_34->setFont(font2);
        pushButton_31 = new QPushButton(Expedientes);
        pushButton_31->setObjectName("pushButton_31");
        pushButton_31->setGeometry(QRect(290, 70, 191, 41));
        pushButton_32 = new QPushButton(Expedientes);
        pushButton_32->setObjectName("pushButton_32");
        pushButton_32->setGeometry(QRect(290, 140, 191, 41));
        pushButton_33 = new QPushButton(Expedientes);
        pushButton_33->setObjectName("pushButton_33");
        pushButton_33->setGeometry(QRect(290, 210, 191, 41));
        stackedWidget->addWidget(Expedientes);
        NuevoExpediente = new QWidget();
        NuevoExpediente->setObjectName("NuevoExpediente");
        label_35 = new QLabel(NuevoExpediente);
        label_35->setObjectName("label_35");
        label_35->setGeometry(QRect(290, 10, 281, 41));
        label_35->setFont(font2);
        label_36 = new QLabel(NuevoExpediente);
        label_36->setObjectName("label_36");
        label_36->setGeometry(QRect(60, 90, 201, 21));
        label_36->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        label_37 = new QLabel(NuevoExpediente);
        label_37->setObjectName("label_37");
        label_37->setGeometry(QRect(60, 130, 121, 16));
        label_37->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        label_38 = new QLabel(NuevoExpediente);
        label_38->setObjectName("label_38");
        label_38->setGeometry(QRect(60, 60, 121, 16));
        label_38->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        label_39 = new QLabel(NuevoExpediente);
        label_39->setObjectName("label_39");
        label_39->setGeometry(QRect(60, 160, 211, 31));
        label_39->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        label_40 = new QLabel(NuevoExpediente);
        label_40->setObjectName("label_40");
        label_40->setGeometry(QRect(500, 90, 101, 31));
        label_40->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        label_41 = new QLabel(NuevoExpediente);
        label_41->setObjectName("label_41");
        label_41->setGeometry(QRect(60, 370, 291, 16));
        label_41->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        label_42 = new QLabel(NuevoExpediente);
        label_42->setObjectName("label_42");
        label_42->setGeometry(QRect(500, 130, 91, 31));
        label_42->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        label_43 = new QLabel(NuevoExpediente);
        label_43->setObjectName("label_43");
        label_43->setGeometry(QRect(60, 410, 271, 16));
        label_43->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        label_44 = new QLabel(NuevoExpediente);
        label_44->setObjectName("label_44");
        label_44->setGeometry(QRect(500, 175, 141, 21));
        label_44->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        label_45 = new QLabel(NuevoExpediente);
        label_45->setObjectName("label_45");
        label_45->setGeometry(QRect(500, 210, 171, 31));
        label_45->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        label_46 = new QLabel(NuevoExpediente);
        label_46->setObjectName("label_46");
        label_46->setGeometry(QRect(500, 260, 191, 16));
        label_46->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        pushButton_34 = new QPushButton(NuevoExpediente);
        pushButton_34->setObjectName("pushButton_34");
        pushButton_34->setGeometry(QRect(400, 500, 91, 41));
        pushButton_35 = new QPushButton(NuevoExpediente);
        pushButton_35->setObjectName("pushButton_35");
        pushButton_35->setGeometry(QRect(759, 503, 121, 41));
        CodigoNextExpedienteLabel = new QLabel(NuevoExpediente);
        CodigoNextExpedienteLabel->setObjectName("CodigoNextExpedienteLabel");
        CodigoNextExpedienteLabel->setGeometry(QRect(130, 60, 49, 16));
        CodigoNextExpedienteLabel->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        NamePacienteCrear = new QLineEdit(NuevoExpediente);
        NamePacienteCrear->setObjectName("NamePacienteCrear");
        NamePacienteCrear->setGeometry(QRect(250, 90, 191, 31));
        NamePacienteCrear->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        IdentidadCrear = new QLineEdit(NuevoExpediente);
        IdentidadCrear->setObjectName("IdentidadCrear");
        IdentidadCrear->setGeometry(QRect(250, 130, 191, 31));
        Telefonocrear = new QLineEdit(NuevoExpediente);
        Telefonocrear->setObjectName("Telefonocrear");
        Telefonocrear->setGeometry(QRect(620, 90, 181, 31));
        EmailCrear = new QLineEdit(NuevoExpediente);
        EmailCrear->setObjectName("EmailCrear");
        EmailCrear->setGeometry(QRect(620, 130, 191, 31));
        contacadiocionalCrear = new QLineEdit(NuevoExpediente);
        contacadiocionalCrear->setObjectName("contacadiocionalCrear");
        contacadiocionalCrear->setGeometry(QRect(350, 370, 211, 31));
        calendarFechaNacimiento = new QCalendarWidget(NuevoExpediente);
        calendarFechaNacimiento->setObjectName("calendarFechaNacimiento");
        calendarFechaNacimiento->setGeometry(QRect(60, 190, 280, 163));
        TelefonoadiocionalCrear = new QLineEdit(NuevoExpediente);
        TelefonoadiocionalCrear->setObjectName("TelefonoadiocionalCrear");
        TelefonoadiocionalCrear->setGeometry(QRect(350, 410, 211, 31));
        AlergiasCrear = new QLineEdit(NuevoExpediente);
        AlergiasCrear->setObjectName("AlergiasCrear");
        AlergiasCrear->setGeometry(QRect(670, 210, 201, 31));
        EnfermedadesCrear = new QLineEdit(NuevoExpediente);
        EnfermedadesCrear->setObjectName("EnfermedadesCrear");
        EnfermedadesCrear->setGeometry(QRect(680, 250, 191, 31));
        TipodeSangreCrear = new QComboBox(NuevoExpediente);
        TipodeSangreCrear->addItem(QString());
        TipodeSangreCrear->addItem(QString());
        TipodeSangreCrear->addItem(QString());
        TipodeSangreCrear->addItem(QString());
        TipodeSangreCrear->addItem(QString());
        TipodeSangreCrear->addItem(QString());
        TipodeSangreCrear->addItem(QString());
        TipodeSangreCrear->addItem(QString());
        TipodeSangreCrear->addItem(QString());
        TipodeSangreCrear->setObjectName("TipodeSangreCrear");
        TipodeSangreCrear->setGeometry(QRect(640, 170, 171, 31));
        label_14 = new QLabel(NuevoExpediente);
        label_14->setObjectName("label_14");
        label_14->setGeometry(QRect(500, 300, 131, 20));
        label_14->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        EncabezadoCrear = new QLineEdit(NuevoExpediente);
        EncabezadoCrear->setObjectName("EncabezadoCrear");
        EncabezadoCrear->setGeometry(QRect(630, 290, 241, 31));
        label_102 = new QLabel(NuevoExpediente);
        label_102->setObjectName("label_102");
        label_102->setGeometry(QRect(60, 450, 261, 16));
        label_102->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        EmailadionalCrear = new QLineEdit(NuevoExpediente);
        EmailadionalCrear->setObjectName("EmailadionalCrear");
        EmailadionalCrear->setGeometry(QRect(350, 450, 211, 31));
        stackedWidget->addWidget(NuevoExpediente);
        AgregardataExp = new QWidget();
        AgregardataExp->setObjectName("AgregardataExp");
        label_48 = new QLabel(AgregardataExp);
        label_48->setObjectName("label_48");
        label_48->setGeometry(QRect(220, 0, 391, 41));
        label_48->setFont(font2);
        label_49 = new QLabel(AgregardataExp);
        label_49->setObjectName("label_49");
        label_49->setGeometry(QRect(680, 40, 71, 16));
        label_49->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        label_50 = new QLabel(AgregardataExp);
        label_50->setObjectName("label_50");
        label_50->setGeometry(QRect(60, 180, 191, 21));
        label_50->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        label_51 = new QLabel(AgregardataExp);
        label_51->setObjectName("label_51");
        label_51->setGeometry(QRect(60, 230, 141, 16));
        label_51->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        label_52 = new QLabel(AgregardataExp);
        label_52->setObjectName("label_52");
        label_52->setGeometry(QRect(60, 260, 201, 21));
        label_52->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        label_53 = new QLabel(AgregardataExp);
        label_53->setObjectName("label_53");
        label_53->setGeometry(QRect(590, 270, 241, 21));
        label_53->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        label_54 = new QLabel(AgregardataExp);
        label_54->setObjectName("label_54");
        label_54->setGeometry(QRect(60, 300, 221, 21));
        label_54->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        Sintomaspresen = new QLineEdit(AgregardataExp);
        Sintomaspresen->setObjectName("Sintomaspresen");
        Sintomaspresen->setGeometry(QRect(280, 180, 251, 31));
        Observacionepaci = new QLineEdit(AgregardataExp);
        Observacionepaci->setObjectName("Observacionepaci");
        Observacionepaci->setGeometry(QRect(280, 220, 251, 31));
        RecomendacionesPaci = new QLineEdit(AgregardataExp);
        RecomendacionesPaci->setObjectName("RecomendacionesPaci");
        RecomendacionesPaci->setGeometry(QRect(280, 260, 251, 31));
        AdicionalComents = new QLineEdit(AgregardataExp);
        AdicionalComents->setObjectName("AdicionalComents");
        AdicionalComents->setGeometry(QRect(280, 300, 251, 31));
        pushButton_36 = new QPushButton(AgregardataExp);
        pushButton_36->setObjectName("pushButton_36");
        pushButton_36->setGeometry(QRect(330, 400, 111, 51));
        pushButton_36->setStyleSheet(QString::fromUtf8("\n"
"font: 700 11pt \"Segoe UI\";"));
        pushButton_37 = new QPushButton(AgregardataExp);
        pushButton_37->setObjectName("pushButton_37");
        pushButton_37->setGeometry(QRect(50, 500, 111, 41));
        label_105 = new QLabel(AgregardataExp);
        label_105->setObjectName("label_105");
        label_105->setGeometry(QRect(60, 100, 191, 16));
        label_105->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        NamePaciente = new QLineEdit(AgregardataExp);
        NamePaciente->setObjectName("NamePaciente");
        NamePaciente->setGeometry(QRect(280, 100, 201, 31));
        label_106 = new QLabel(AgregardataExp);
        label_106->setObjectName("label_106");
        label_106->setGeometry(QRect(60, 140, 201, 16));
        label_106->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        IdentidadPaciente = new QLineEdit(AgregardataExp);
        IdentidadPaciente->setObjectName("IdentidadPaciente");
        IdentidadPaciente->setGeometry(QRect(280, 140, 201, 31));
        label_107 = new QLabel(AgregardataExp);
        label_107->setObjectName("label_107");
        label_107->setGeometry(QRect(60, 340, 141, 16));
        label_107->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        labelDiagnostico = new QLineEdit(AgregardataExp);
        labelDiagnostico->setObjectName("labelDiagnostico");
        labelDiagnostico->setGeometry(QRect(280, 340, 251, 41));
        feachaDeCita = new QCalendarWidget(AgregardataExp);
        feachaDeCita->setObjectName("feachaDeCita");
        feachaDeCita->setGeometry(QRect(550, 60, 304, 173));
        ProximaCita = new QCalendarWidget(AgregardataExp);
        ProximaCita->setObjectName("ProximaCita");
        ProximaCita->setGeometry(QRect(550, 300, 311, 171));
        stackedWidget->addWidget(AgregardataExp);
        Recetas = new QWidget();
        Recetas->setObjectName("Recetas");
        label_55 = new QLabel(Recetas);
        label_55->setObjectName("label_55");
        label_55->setGeometry(QRect(320, 10, 111, 31));
        label_55->setFont(font2);
        pushButton_38 = new QPushButton(Recetas);
        pushButton_38->setObjectName("pushButton_38");
        pushButton_38->setGeometry(QRect(280, 60, 191, 41));
        pushButton_39 = new QPushButton(Recetas);
        pushButton_39->setObjectName("pushButton_39");
        pushButton_39->setGeometry(QRect(280, 130, 191, 41));
        pushButton_40 = new QPushButton(Recetas);
        pushButton_40->setObjectName("pushButton_40");
        pushButton_40->setGeometry(QRect(280, 200, 191, 41));
        stackedWidget->addWidget(Recetas);
        NuevaReceta = new QWidget();
        NuevaReceta->setObjectName("NuevaReceta");
        label_56 = new QLabel(NuevaReceta);
        label_56->setObjectName("label_56");
        label_56->setGeometry(QRect(320, 10, 151, 41));
        label_56->setFont(font2);
        label_57 = new QLabel(NuevaReceta);
        label_57->setObjectName("label_57");
        label_57->setGeometry(QRect(50, 70, 49, 16));
        label_58 = new QLabel(NuevaReceta);
        label_58->setObjectName("label_58");
        label_58->setGeometry(QRect(50, 130, 49, 16));
        label_59 = new QLabel(NuevaReceta);
        label_59->setObjectName("label_59");
        label_59->setGeometry(QRect(50, 200, 121, 21));
        paciente_cb = new QComboBox(NuevaReceta);
        paciente_cb->setObjectName("paciente_cb");
        paciente_cb->setGeometry(QRect(100, 120, 181, 31));
        medicamento_cb = new QComboBox(NuevaReceta);
        medicamento_cb->addItem(QString());
        medicamento_cb->addItem(QString());
        medicamento_cb->addItem(QString());
        medicamento_cb->addItem(QString());
        medicamento_cb->addItem(QString());
        medicamento_cb->addItem(QString());
        medicamento_cb->addItem(QString());
        medicamento_cb->addItem(QString());
        medicamento_cb->addItem(QString());
        medicamento_cb->addItem(QString());
        medicamento_cb->setObjectName("medicamento_cb");
        medicamento_cb->setGeometry(QRect(170, 200, 181, 31));
        lb_fecha_actual = new QLabel(NuevaReceta);
        lb_fecha_actual->setObjectName("lb_fecha_actual");
        lb_fecha_actual->setGeometry(QRect(100, 70, 49, 16));
        pushButton_41 = new QPushButton(NuevaReceta);
        pushButton_41->setObjectName("pushButton_41");
        pushButton_41->setGeometry(QRect(30, 510, 80, 24));
        new_recipe = new QPushButton(NuevaReceta);
        new_recipe->setObjectName("new_recipe");
        new_recipe->setGeometry(QRect(340, 310, 80, 24));
        label_60 = new QLabel(NuevaReceta);
        label_60->setObjectName("label_60");
        label_60->setGeometry(QRect(50, 260, 121, 21));
        dosis_cb = new QComboBox(NuevaReceta);
        dosis_cb->addItem(QString());
        dosis_cb->addItem(QString());
        dosis_cb->addItem(QString());
        dosis_cb->addItem(QString());
        dosis_cb->addItem(QString());
        dosis_cb->addItem(QString());
        dosis_cb->addItem(QString());
        dosis_cb->addItem(QString());
        dosis_cb->addItem(QString());
        dosis_cb->setObjectName("dosis_cb");
        dosis_cb->setGeometry(QRect(170, 260, 181, 31));
        stackedWidget->addWidget(NuevaReceta);
        BuscarReceta = new QWidget();
        BuscarReceta->setObjectName("BuscarReceta");
        label_61 = new QLabel(BuscarReceta);
        label_61->setObjectName("label_61");
        label_61->setGeometry(QRect(300, 10, 151, 41));
        label_61->setFont(font2);
        radioButton = new QRadioButton(BuscarReceta);
        radioButton->setObjectName("radioButton");
        radioButton->setGeometry(QRect(50, 70, 91, 22));
        radioButton_2 = new QRadioButton(BuscarReceta);
        radioButton_2->setObjectName("radioButton_2");
        radioButton_2->setGeometry(QRect(500, 60, 91, 22));
        calendarWidget_6 = new QCalendarWidget(BuscarReceta);
        calendarWidget_6->setObjectName("calendarWidget_6");
        calendarWidget_6->setGeometry(QRect(480, 90, 281, 201));
        comboBox_4 = new QComboBox(BuscarReceta);
        comboBox_4->setObjectName("comboBox_4");
        comboBox_4->setGeometry(QRect(130, 70, 171, 21));
        pushButton_43 = new QPushButton(BuscarReceta);
        pushButton_43->setObjectName("pushButton_43");
        pushButton_43->setGeometry(QRect(340, 70, 80, 24));
        pushButton_44 = new QPushButton(BuscarReceta);
        pushButton_44->setObjectName("pushButton_44");
        pushButton_44->setGeometry(QRect(30, 500, 80, 24));
        textBrowser = new QTextBrowser(BuscarReceta);
        textBrowser->setObjectName("textBrowser");
        textBrowser->setGeometry(QRect(210, 200, 256, 192));
        label_62 = new QLabel(BuscarReceta);
        label_62->setObjectName("label_62");
        label_62->setGeometry(QRect(320, 180, 49, 16));
        stackedWidget->addWidget(BuscarReceta);
        Reservaciones = new QWidget();
        Reservaciones->setObjectName("Reservaciones");
        label_63 = new QLabel(Reservaciones);
        label_63->setObjectName("label_63");
        label_63->setGeometry(QRect(290, 10, 201, 41));
        label_63->setFont(font2);
        pushButton_45 = new QPushButton(Reservaciones);
        pushButton_45->setObjectName("pushButton_45");
        pushButton_45->setGeometry(QRect(290, 80, 191, 41));
        pushButton_46 = new QPushButton(Reservaciones);
        pushButton_46->setObjectName("pushButton_46");
        pushButton_46->setGeometry(QRect(290, 140, 191, 41));
        pushButton_47 = new QPushButton(Reservaciones);
        pushButton_47->setObjectName("pushButton_47");
        pushButton_47->setGeometry(QRect(290, 200, 191, 41));
        pushButton_48 = new QPushButton(Reservaciones);
        pushButton_48->setObjectName("pushButton_48");
        pushButton_48->setGeometry(QRect(290, 260, 191, 41));
        stackedWidget->addWidget(Reservaciones);
        NuevaReservacion = new QWidget();
        NuevaReservacion->setObjectName("NuevaReservacion");
        label_64 = new QLabel(NuevaReservacion);
        label_64->setObjectName("label_64");
        label_64->setGeometry(QRect(300, 10, 271, 31));
        label_64->setFont(font2);
        label_65 = new QLabel(NuevaReservacion);
        label_65->setObjectName("label_65");
        label_65->setGeometry(QRect(100, 70, 49, 16));
        label_65->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        salas_cb = new QComboBox(NuevaReservacion);
        salas_cb->setObjectName("salas_cb");
        salas_cb->setGeometry(QRect(160, 60, 151, 31));
        label_66 = new QLabel(NuevaReservacion);
        label_66->setObjectName("label_66");
        label_66->setGeometry(QRect(100, 110, 191, 31));
        label_66->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        date_reserva = new QDateEdit(NuevaReservacion);
        date_reserva->setObjectName("date_reserva");
        date_reserva->setGeometry(QRect(240, 150, 161, 41));
        label_67 = new QLabel(NuevaReservacion);
        label_67->setObjectName("label_67");
        label_67->setGeometry(QRect(100, 160, 81, 21));
        label_67->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        label_68 = new QLabel(NuevaReservacion);
        label_68->setObjectName("label_68");
        label_68->setGeometry(QRect(100, 200, 161, 31));
        label_68->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        Hora_inicio = new QTimeEdit(NuevaReservacion);
        Hora_inicio->setObjectName("Hora_inicio");
        Hora_inicio->setGeometry(QRect(240, 200, 161, 41));
        Hora_final = new QTimeEdit(NuevaReservacion);
        Hora_final->setObjectName("Hora_final");
        Hora_final->setGeometry(QRect(240, 260, 161, 41));
        txt_name = new QLineEdit(NuevaReservacion);
        txt_name->setObjectName("txt_name");
        txt_name->setGeometry(QRect(290, 110, 211, 31));
        label_69 = new QLabel(NuevaReservacion);
        label_69->setObjectName("label_69");
        label_69->setGeometry(QRect(100, 260, 101, 31));
        label_69->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        txtnamedoctor = new QLineEdit(NuevaReservacion);
        txtnamedoctor->setObjectName("txtnamedoctor");
        txtnamedoctor->setGeometry(QRect(280, 320, 161, 31));
        label_70 = new QLabel(NuevaReservacion);
        label_70->setObjectName("label_70");
        label_70->setGeometry(QRect(100, 320, 191, 21));
        label_70->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        bt_reservar = new QPushButton(NuevaReservacion);
        bt_reservar->setObjectName("bt_reservar");
        bt_reservar->setGeometry(QRect(350, 450, 91, 41));
        pushButton_50 = new QPushButton(NuevaReservacion);
        pushButton_50->setObjectName("pushButton_50");
        pushButton_50->setGeometry(QRect(760, 480, 111, 41));
        txtobservaciones = new QLineEdit(NuevaReservacion);
        txtobservaciones->setObjectName("txtobservaciones");
        txtobservaciones->setGeometry(QRect(280, 370, 161, 41));
        label_108 = new QLabel(NuevaReservacion);
        label_108->setObjectName("label_108");
        label_108->setGeometry(QRect(100, 370, 141, 31));
        label_108->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        label_109 = new QLabel(NuevaReservacion);
        label_109->setObjectName("label_109");
        label_109->setGeometry(QRect(630, 60, 63, 20));
        lbcodereservas = new QLabel(NuevaReservacion);
        lbcodereservas->setObjectName("lbcodereservas");
        lbcodereservas->setGeometry(QRect(690, 60, 63, 20));
        stackedWidget->addWidget(NuevaReservacion);
        ModificarReserva = new QWidget();
        ModificarReserva->setObjectName("ModificarReserva");
        label_71 = new QLabel(ModificarReserva);
        label_71->setObjectName("label_71");
        label_71->setGeometry(QRect(330, 10, 241, 31));
        label_71->setFont(font2);
        label_72 = new QLabel(ModificarReserva);
        label_72->setObjectName("label_72");
        label_72->setGeometry(QRect(250, 130, 191, 21));
        label_72->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        txtnombreMR = new QLineEdit(ModificarReserva);
        txtnombreMR->setObjectName("txtnombreMR");
        txtnombreMR->setGeometry(QRect(440, 130, 191, 31));
        label_73 = new QLabel(ModificarReserva);
        label_73->setObjectName("label_73");
        label_73->setGeometry(QRect(250, 180, 49, 16));
        label_73->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        FechaMR = new QDateEdit(ModificarReserva);
        FechaMR->setObjectName("FechaMR");
        FechaMR->setGeometry(QRect(440, 170, 151, 41));
        label_74 = new QLabel(ModificarReserva);
        label_74->setObjectName("label_74");
        label_74->setGeometry(QRect(250, 220, 141, 31));
        label_74->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        HoraIMR = new QTimeEdit(ModificarReserva);
        HoraIMR->setObjectName("HoraIMR");
        HoraIMR->setGeometry(QRect(440, 220, 151, 41));
        HoraFMR = new QTimeEdit(ModificarReserva);
        HoraFMR->setObjectName("HoraFMR");
        HoraFMR->setGeometry(QRect(440, 270, 151, 41));
        label_75 = new QLabel(ModificarReserva);
        label_75->setObjectName("label_75");
        label_75->setGeometry(QRect(250, 270, 111, 31));
        label_75->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        label_76 = new QLabel(ModificarReserva);
        label_76->setObjectName("label_76");
        label_76->setGeometry(QRect(240, 310, 181, 41));
        label_76->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        nameDoctorMR = new QLineEdit(ModificarReserva);
        nameDoctorMR->setObjectName("nameDoctorMR");
        nameDoctorMR->setGeometry(QRect(440, 320, 191, 31));
        btmodificarR = new QPushButton(ModificarReserva);
        btmodificarR->setObjectName("btmodificarR");
        btmodificarR->setGeometry(QRect(370, 500, 141, 41));
        pushButton_52 = new QPushButton(ModificarReserva);
        pushButton_52->setObjectName("pushButton_52");
        pushButton_52->setGeometry(QRect(730, 480, 121, 41));
        label_110 = new QLabel(ModificarReserva);
        label_110->setObjectName("label_110");
        label_110->setGeometry(QRect(250, 70, 63, 20));
        label_110->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        txtcodereserva = new QLineEdit(ModificarReserva);
        txtcodereserva->setObjectName("txtcodereserva");
        txtcodereserva->setGeometry(QRect(330, 70, 113, 28));
        label_111 = new QLabel(ModificarReserva);
        label_111->setObjectName("label_111");
        label_111->setGeometry(QRect(240, 370, 151, 31));
        label_111->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        txtobeservacionesMR = new QTextEdit(ModificarReserva);
        txtobeservacionesMR->setObjectName("txtobeservacionesMR");
        txtobeservacionesMR->setGeometry(QRect(440, 360, 221, 101));
        bt_buscarMR = new QPushButton(ModificarReserva);
        bt_buscarMR->setObjectName("bt_buscarMR");
        bt_buscarMR->setGeometry(QRect(460, 70, 83, 29));
        stackedWidget->addWidget(ModificarReserva);
        EliminarReserva = new QWidget();
        EliminarReserva->setObjectName("EliminarReserva");
        label_77 = new QLabel(EliminarReserva);
        label_77->setObjectName("label_77");
        label_77->setGeometry(QRect(290, 10, 221, 21));
        label_77->setFont(font2);
        label_78 = new QLabel(EliminarReserva);
        label_78->setObjectName("label_78");
        label_78->setGeometry(QRect(210, 100, 141, 21));
        label_78->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        comboBox_6 = new QComboBox(EliminarReserva);
        comboBox_6->setObjectName("comboBox_6");
        comboBox_6->setGeometry(QRect(370, 100, 161, 31));
        bt_EliminarR = new QPushButton(EliminarReserva);
        bt_EliminarR->setObjectName("bt_EliminarR");
        bt_EliminarR->setGeometry(QRect(360, 200, 111, 41));
        pushButton_54 = new QPushButton(EliminarReserva);
        pushButton_54->setObjectName("pushButton_54");
        pushButton_54->setGeometry(QRect(720, 480, 121, 41));
        txtcodeER = new QLineEdit(EliminarReserva);
        txtcodeER->setObjectName("txtcodeER");
        txtcodeER->setGeometry(QRect(370, 140, 161, 41));
        label_112 = new QLabel(EliminarReserva);
        label_112->setObjectName("label_112");
        label_112->setGeometry(QRect(210, 150, 63, 20));
        stackedWidget->addWidget(EliminarReserva);
        AgendaConsulta = new QWidget();
        AgendaConsulta->setObjectName("AgendaConsulta");
        label_79 = new QLabel(AgendaConsulta);
        label_79->setObjectName("label_79");
        label_79->setGeometry(QRect(260, 10, 281, 41));
        label_79->setFont(font2);
        pushButton_55 = new QPushButton(AgendaConsulta);
        pushButton_55->setObjectName("pushButton_55");
        pushButton_55->setGeometry(QRect(300, 70, 191, 41));
        pushButton_56 = new QPushButton(AgendaConsulta);
        pushButton_56->setObjectName("pushButton_56");
        pushButton_56->setGeometry(QRect(300, 130, 191, 41));
        pushButton_57 = new QPushButton(AgendaConsulta);
        pushButton_57->setObjectName("pushButton_57");
        pushButton_57->setGeometry(QRect(300, 190, 191, 41));
        pushButton_58 = new QPushButton(AgendaConsulta);
        pushButton_58->setObjectName("pushButton_58");
        pushButton_58->setGeometry(QRect(300, 250, 191, 41));
        pushButton_59 = new QPushButton(AgendaConsulta);
        pushButton_59->setObjectName("pushButton_59");
        pushButton_59->setGeometry(QRect(300, 310, 191, 41));
        stackedWidget->addWidget(AgendaConsulta);
        NuevaCita = new QWidget();
        NuevaCita->setObjectName("NuevaCita");
        label_80 = new QLabel(NuevaCita);
        label_80->setObjectName("label_80");
        label_80->setGeometry(QRect(350, 0, 191, 41));
        label_80->setFont(font2);
        label_81 = new QLabel(NuevaCita);
        label_81->setObjectName("label_81");
        label_81->setGeometry(QRect(90, 80, 121, 31));
        label_81->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 16pt \"Segoe UI\";"));
        label_82 = new QLabel(NuevaCita);
        label_82->setObjectName("label_82");
        label_82->setGeometry(QRect(90, 130, 91, 31));
        label_82->setStyleSheet(QString::fromUtf8("font: 16pt \"Segoe UI\";\n"
"color: rgb(0, 0, 0);"));
        label_83 = new QLabel(NuevaCita);
        label_83->setObjectName("label_83");
        label_83->setGeometry(QRect(90, 180, 91, 31));
        label_83->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 16pt \"Segoe UI\";"));
        txtnombrecita = new QLineEdit(NuevaCita);
        txtnombrecita->setObjectName("txtnombrecita");
        txtnombrecita->setGeometry(QRect(210, 80, 181, 31));
        dateCita = new QDateEdit(NuevaCita);
        dateCita->setObjectName("dateCita");
        dateCita->setGeometry(QRect(210, 130, 181, 41));
        TimeCita = new QTimeEdit(NuevaCita);
        TimeCita->setObjectName("TimeCita");
        TimeCita->setGeometry(QRect(210, 180, 181, 41));
        btNewCita = new QPushButton(NuevaCita);
        btNewCita->setObjectName("btNewCita");
        btNewCita->setGeometry(QRect(360, 260, 91, 41));
        pushButton_61 = new QPushButton(NuevaCita);
        pushButton_61->setObjectName("pushButton_61");
        pushButton_61->setGeometry(QRect(660, 490, 111, 41));
        stackedWidget->addWidget(NuevaCita);
        ModificarCita = new QWidget();
        ModificarCita->setObjectName("ModificarCita");
        label_84 = new QLabel(ModificarCita);
        label_84->setObjectName("label_84");
        label_84->setGeometry(QRect(330, 10, 231, 41));
        label_84->setFont(font2);
        label_85 = new QLabel(ModificarCita);
        label_85->setObjectName("label_85");
        label_85->setGeometry(QRect(300, 110, 49, 16));
        label_85->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        comboBox_7 = new QComboBox(ModificarCita);
        comboBox_7->setObjectName("comboBox_7");
        comboBox_7->setGeometry(QRect(390, 110, 181, 31));
        label_86 = new QLabel(ModificarCita);
        label_86->setObjectName("label_86");
        label_86->setGeometry(QRect(300, 230, 49, 16));
        label_86->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        label_87 = new QLabel(ModificarCita);
        label_87->setObjectName("label_87");
        label_87->setGeometry(QRect(300, 170, 49, 16));
        label_87->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        dateEdit_6 = new QDateEdit(ModificarCita);
        dateEdit_6->setObjectName("dateEdit_6");
        dateEdit_6->setGeometry(QRect(390, 160, 181, 41));
        timeEdit_6 = new QTimeEdit(ModificarCita);
        timeEdit_6->setObjectName("timeEdit_6");
        timeEdit_6->setGeometry(QRect(390, 220, 181, 41));
        pushButton_62 = new QPushButton(ModificarCita);
        pushButton_62->setObjectName("pushButton_62");
        pushButton_62->setGeometry(QRect(390, 310, 121, 41));
        pushButton_63 = new QPushButton(ModificarCita);
        pushButton_63->setObjectName("pushButton_63");
        pushButton_63->setGeometry(QRect(730, 480, 141, 41));
        stackedWidget->addWidget(ModificarCita);
        EliminarCita = new QWidget();
        EliminarCita->setObjectName("EliminarCita");
        label_88 = new QLabel(EliminarCita);
        label_88->setObjectName("label_88");
        label_88->setGeometry(QRect(330, 10, 211, 61));
        label_88->setFont(font2);
        label_89 = new QLabel(EliminarCita);
        label_89->setObjectName("label_89");
        label_89->setGeometry(QRect(300, 140, 71, 31));
        label_89->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        pushButton_64 = new QPushButton(EliminarCita);
        pushButton_64->setObjectName("pushButton_64");
        pushButton_64->setGeometry(QRect(360, 250, 131, 41));
        pushButton_65 = new QPushButton(EliminarCita);
        pushButton_65->setObjectName("pushButton_65");
        pushButton_65->setGeometry(QRect(740, 480, 121, 41));
        comboBox_8 = new QComboBox(EliminarCita);
        comboBox_8->setObjectName("comboBox_8");
        comboBox_8->setGeometry(QRect(380, 140, 181, 31));
        stackedWidget->addWidget(EliminarCita);
        ConsultarCita = new QWidget();
        ConsultarCita->setObjectName("ConsultarCita");
        label_90 = new QLabel(ConsultarCita);
        label_90->setObjectName("label_90");
        label_90->setGeometry(QRect(340, 10, 211, 41));
        label_90->setFont(font2);
        label_91 = new QLabel(ConsultarCita);
        label_91->setObjectName("label_91");
        label_91->setGeometry(QRect(200, 120, 91, 21));
        label_91->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        pushButton_66 = new QPushButton(ConsultarCita);
        pushButton_66->setObjectName("pushButton_66");
        pushButton_66->setGeometry(QRect(490, 110, 111, 41));
        textBrowser_2 = new QTextBrowser(ConsultarCita);
        textBrowser_2->setObjectName("textBrowser_2");
        textBrowser_2->setGeometry(QRect(200, 180, 501, 211));
        pushButton_67 = new QPushButton(ConsultarCita);
        pushButton_67->setObjectName("pushButton_67");
        pushButton_67->setGeometry(QRect(750, 480, 111, 41));
        dateEdit_7 = new QDateEdit(ConsultarCita);
        dateEdit_7->setObjectName("dateEdit_7");
        dateEdit_7->setGeometry(QRect(280, 110, 151, 41));
        stackedWidget->addWidget(ConsultarCita);
        OpcionesDeUsuario = new QWidget();
        OpcionesDeUsuario->setObjectName("OpcionesDeUsuario");
        label_92 = new QLabel(OpcionesDeUsuario);
        label_92->setObjectName("label_92");
        label_92->setGeometry(QRect(290, 10, 281, 51));
        label_92->setFont(font2);
        pushButton_68 = new QPushButton(OpcionesDeUsuario);
        pushButton_68->setObjectName("pushButton_68");
        pushButton_68->setGeometry(QRect(350, 120, 191, 41));
        pushButton_69 = new QPushButton(OpcionesDeUsuario);
        pushButton_69->setObjectName("pushButton_69");
        pushButton_69->setGeometry(QRect(350, 190, 191, 41));
        stackedWidget->addWidget(OpcionesDeUsuario);
        CambiarPassword = new QWidget();
        CambiarPassword->setObjectName("CambiarPassword");
        label_93 = new QLabel(CambiarPassword);
        label_93->setObjectName("label_93");
        label_93->setGeometry(QRect(310, 10, 271, 61));
        label_93->setFont(font2);
        label_94 = new QLabel(CambiarPassword);
        label_94->setObjectName("label_94");
        label_94->setGeometry(QRect(240, 110, 191, 16));
        label_94->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        label_95 = new QLabel(CambiarPassword);
        label_95->setObjectName("label_95");
        label_95->setGeometry(QRect(60, 120, 49, 16));
        label_96 = new QLabel(CambiarPassword);
        label_96->setObjectName("label_96");
        label_96->setGeometry(QRect(240, 150, 171, 16));
        label_96->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        pushButton_70 = new QPushButton(CambiarPassword);
        pushButton_70->setObjectName("pushButton_70");
        pushButton_70->setGeometry(QRect(410, 240, 111, 41));
        pushButton_71 = new QPushButton(CambiarPassword);
        pushButton_71->setObjectName("pushButton_71");
        pushButton_71->setGeometry(QRect(750, 480, 101, 41));
        ActualPasswordUser = new QLineEdit(CambiarPassword);
        ActualPasswordUser->setObjectName("ActualPasswordUser");
        ActualPasswordUser->setGeometry(QRect(420, 100, 241, 31));
        NewPasswordUser = new QLineEdit(CambiarPassword);
        NewPasswordUser->setObjectName("NewPasswordUser");
        NewPasswordUser->setGeometry(QRect(420, 140, 241, 31));
        label_47 = new QLabel(CambiarPassword);
        label_47->setObjectName("label_47");
        label_47->setGeometry(QRect(250, 60, 441, 16));
        stackedWidget->addWidget(CambiarPassword);
        Reportes = new QWidget();
        Reportes->setObjectName("Reportes");
        label_97 = new QLabel(Reportes);
        label_97->setObjectName("label_97");
        label_97->setGeometry(QRect(350, 10, 181, 51));
        label_97->setFont(font2);
        pushButton_72 = new QPushButton(Reportes);
        pushButton_72->setObjectName("pushButton_72");
        pushButton_72->setGeometry(QRect(310, 80, 191, 41));
        pushButton_73 = new QPushButton(Reportes);
        pushButton_73->setObjectName("pushButton_73");
        pushButton_73->setGeometry(QRect(310, 180, 191, 41));
        pushButton_78 = new QPushButton(Reportes);
        pushButton_78->setObjectName("pushButton_78");
        pushButton_78->setGeometry(QRect(310, 260, 191, 41));
        stackedWidget->addWidget(Reportes);
        ReportePacientes = new QWidget();
        ReportePacientes->setObjectName("ReportePacientes");
        label_98 = new QLabel(ReportePacientes);
        label_98->setObjectName("label_98");
        label_98->setGeometry(QRect(340, 10, 131, 31));
        label_98->setFont(font2);
        textBrowser_3 = new QTextBrowser(ReportePacientes);
        textBrowser_3->setObjectName("textBrowser_3");
        textBrowser_3->setGeometry(QRect(290, 160, 256, 192));
        label_99 = new QLabel(ReportePacientes);
        label_99->setObjectName("label_99");
        label_99->setGeometry(QRect(60, 80, 49, 16));
        dateEdit_8 = new QDateEdit(ReportePacientes);
        dateEdit_8->setObjectName("dateEdit_8");
        dateEdit_8->setGeometry(QRect(130, 70, 110, 25));
        pushButton_74 = new QPushButton(ReportePacientes);
        pushButton_74->setObjectName("pushButton_74");
        pushButton_74->setGeometry(QRect(360, 120, 80, 24));
        pushButton_75 = new QPushButton(ReportePacientes);
        pushButton_75->setObjectName("pushButton_75");
        pushButton_75->setGeometry(QRect(60, 470, 80, 24));
        stackedWidget->addWidget(ReportePacientes);
        ReporteCitas = new QWidget();
        ReporteCitas->setObjectName("ReporteCitas");
        label_100 = new QLabel(ReporteCitas);
        label_100->setObjectName("label_100");
        label_100->setGeometry(QRect(370, 10, 81, 31));
        label_100->setFont(font2);
        label_101 = new QLabel(ReporteCitas);
        label_101->setObjectName("label_101");
        label_101->setGeometry(QRect(60, 90, 49, 16));
        dateEdit_9 = new QDateEdit(ReporteCitas);
        dateEdit_9->setObjectName("dateEdit_9");
        dateEdit_9->setGeometry(QRect(110, 90, 110, 25));
        pushButton_76 = new QPushButton(ReporteCitas);
        pushButton_76->setObjectName("pushButton_76");
        pushButton_76->setGeometry(QRect(360, 160, 80, 24));
        textBrowser_4 = new QTextBrowser(ReporteCitas);
        textBrowser_4->setObjectName("textBrowser_4");
        textBrowser_4->setGeometry(QRect(290, 210, 271, 211));
        pushButton_77 = new QPushButton(ReporteCitas);
        pushButton_77->setObjectName("pushButton_77");
        pushButton_77->setGeometry(QRect(70, 480, 80, 24));
        stackedWidget->addWidget(ReporteCitas);
        AgregarRoll = new QWidget();
        AgregarRoll->setObjectName("AgregarRoll");
        label_103 = new QLabel(AgregarRoll);
        label_103->setObjectName("label_103");
        label_103->setGeometry(QRect(360, 40, 251, 61));
        label_103->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 24pt \"Segoe UI\";"));
        label_104 = new QLabel(AgregarRoll);
        label_104->setObjectName("label_104");
        label_104->setGeometry(QRect(250, 140, 221, 41));
        label_104->setStyleSheet(QString::fromUtf8("color: rgb(0, 0, 0);\n"
"font: 700 11pt \"Segoe UI\";"));
        otroRole = new QLineEdit(AgregarRoll);
        otroRole->setObjectName("otroRole");
        otroRole->setGeometry(QRect(440, 140, 231, 41));
        pushButton_80 = new QPushButton(AgregarRoll);
        pushButton_80->setObjectName("pushButton_80");
        pushButton_80->setGeometry(QRect(380, 420, 111, 41));
        checkBox = new QCheckBox(AgregarRoll);
        checkBox->setObjectName("checkBox");
        checkBox->setGeometry(QRect(530, 220, 171, 20));
        stackedWidget->addWidget(AgregarRoll);
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName("menubar");
        menubar->setGeometry(QRect(0, 0, 875, 21));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName("statusbar");
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        stackedWidget->setCurrentIndex(8);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "Login", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "Ingrese su cuenta:", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "Ingrese su password:", nullptr));
        pushButton->setText(QCoreApplication::translate("MainWindow", "Login", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindow", "Registro", nullptr));
        label_5->setText(QCoreApplication::translate("MainWindow", "Nombre:", nullptr));
        label_6->setText(QCoreApplication::translate("MainWindow", "Rol:", nullptr));
        label_7->setText(QCoreApplication::translate("MainWindow", "User:", nullptr));
        pushButton_2->setText(QCoreApplication::translate("MainWindow", "Crear", nullptr));
        pushButton_3->setText(QCoreApplication::translate("MainWindow", "Login", nullptr));
        pushButton_4->setText(QCoreApplication::translate("MainWindow", "Administraci\303\263n del Sistema", nullptr));
        pushButton_5->setText(QCoreApplication::translate("MainWindow", "Administraci\303\263n de Salas", nullptr));
        pushButton_6->setText(QCoreApplication::translate("MainWindow", "Expedientes", nullptr));
        pushButton_7->setText(QCoreApplication::translate("MainWindow", "Recetas", nullptr));
        pushButton_8->setText(QCoreApplication::translate("MainWindow", "Reservaciones", nullptr));
        pushButton_9->setText(QCoreApplication::translate("MainWindow", "Agente de Consultas", nullptr));
        pushButton_10->setText(QCoreApplication::translate("MainWindow", "Opciones de Usuario", nullptr));
        pushButton_11->setText(QCoreApplication::translate("MainWindow", "Reportes", nullptr));
        pushButton_12->setText(QCoreApplication::translate("MainWindow", "Salir", nullptr));
        label_8->setText(QCoreApplication::translate("MainWindow", "Men\303\272 Principal", nullptr));
        label_9->setText(QCoreApplication::translate("MainWindow", "Administraci\303\263n del Sistema", nullptr));
        pushButton_13->setText(QCoreApplication::translate("MainWindow", "Crear nuevo usuario", nullptr));
        pushButton_14->setText(QCoreApplication::translate("MainWindow", "Dar baja a un usuario", nullptr));
        pushButton_15->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        pushButton_79->setText(QCoreApplication::translate("MainWindow", "Agregar rol", nullptr));
        label_10->setText(QCoreApplication::translate("MainWindow", "Crear Nuevo Usuario", nullptr));
        label_11->setText(QCoreApplication::translate("MainWindow", "Nombre:", nullptr));
        label_12->setText(QCoreApplication::translate("MainWindow", "Cuenta:", nullptr));
        label_13->setText(QCoreApplication::translate("MainWindow", "Rol:", nullptr));
        pushButton_16->setText(QCoreApplication::translate("MainWindow", "Crear", nullptr));
        pushButton_17->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        pushButton_18->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_15->setText(QCoreApplication::translate("MainWindow", "Dar de baja a Usuario", nullptr));
        label_16->setText(QCoreApplication::translate("MainWindow", "Nombre:", nullptr));
        pushButton_19->setText(QCoreApplication::translate("MainWindow", "Dar de baja", nullptr));
        label_17->setText(QCoreApplication::translate("MainWindow", "Usuario:", nullptr));
        label_18->setText(QCoreApplication::translate("MainWindow", "Administraci\303\263n de Salas ", nullptr));
        pushButton_20->setText(QCoreApplication::translate("MainWindow", "Crear nueva sala", nullptr));
        pushButton_21->setText(QCoreApplication::translate("MainWindow", "Modificar sala", nullptr));
        pushButton_22->setText(QCoreApplication::translate("MainWindow", "Eliminar sala", nullptr));
        pushButton_23->setText(QCoreApplication::translate("MainWindow", "Regresar ", nullptr));
        label_19->setText(QCoreApplication::translate("MainWindow", "Crear Nueva Sala", nullptr));
        label_20->setText(QCoreApplication::translate("MainWindow", "C\303\263digo:", nullptr));
        label_21->setText(QCoreApplication::translate("MainWindow", "Descripci\303\263n:", nullptr));
        label_22->setText(QCoreApplication::translate("MainWindow", "Status:", nullptr));
        label_23->setText(QCoreApplication::translate("MainWindow", "Fecha de Inicio:", nullptr));
        label_24->setText(QCoreApplication::translate("MainWindow", "Fin de Disponibilidad:", nullptr));
        pushButton_24->setText(QCoreApplication::translate("MainWindow", "Crear", nullptr));
        pushButton_25->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        lbcodesala->setText(QString());
        label_113->setText(QCoreApplication::translate("MainWindow", "Hora de disponibilidad:", nullptr));
        label_114->setText(QCoreApplication::translate("MainWindow", "Hora final de disponibilidad:", nullptr));
        lb_status->setText(QString());
        label_25->setText(QCoreApplication::translate("MainWindow", "Modificar Sala", nullptr));
        label_26->setText(QCoreApplication::translate("MainWindow", "Codigo:", nullptr));
        label_27->setText(QCoreApplication::translate("MainWindow", "Descripci\303\263n:", nullptr));
        label_28->setText(QCoreApplication::translate("MainWindow", "Status:", nullptr));
        label_29->setText(QCoreApplication::translate("MainWindow", "Fecha de Inicio:", nullptr));
        label_30->setText(QCoreApplication::translate("MainWindow", "Fin de Disponibilidad:", nullptr));
        pushButton_26->setText(QCoreApplication::translate("MainWindow", "Modificar", nullptr));
        pushButton_27->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_115->setText(QCoreApplication::translate("MainWindow", "Hora de disponibilidad:", nullptr));
        label_116->setText(QCoreApplication::translate("MainWindow", "Hora Final de de Disponiblidad:", nullptr));
        buscar_sala->setText(QCoreApplication::translate("MainWindow", "Buscar", nullptr));
        label_31->setText(QCoreApplication::translate("MainWindow", "Eliminar Sala", nullptr));
        label_32->setText(QCoreApplication::translate("MainWindow", "C\303\263digo de Sala:", nullptr));
        pushButton_28->setText(QCoreApplication::translate("MainWindow", "Buscar", nullptr));
        label_33->setText(QCoreApplication::translate("MainWindow", "Usuario:", nullptr));
        EliminarSala->setText(QCoreApplication::translate("MainWindow", "Eliminar", nullptr));
        pushButton_30->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_34->setText(QCoreApplication::translate("MainWindow", "Expedientes", nullptr));
        pushButton_31->setText(QCoreApplication::translate("MainWindow", "Nuevo Expediente", nullptr));
        pushButton_32->setText(QCoreApplication::translate("MainWindow", "Agregar Datos al Expediente", nullptr));
        pushButton_33->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_35->setText(QCoreApplication::translate("MainWindow", "Nuevo Expediente", nullptr));
        label_36->setText(QCoreApplication::translate("MainWindow", "Nombre del paciente:", nullptr));
        label_37->setText(QCoreApplication::translate("MainWindow", "Identidad:", nullptr));
        label_38->setText(QCoreApplication::translate("MainWindow", "C\303\263digo:", nullptr));
        label_39->setText(QCoreApplication::translate("MainWindow", "Fecha de nacimiento:", nullptr));
        label_40->setText(QCoreApplication::translate("MainWindow", "Telefono 1:", nullptr));
        label_41->setText(QCoreApplication::translate("MainWindow", "Nombre del contacto adicional:", nullptr));
        label_42->setText(QCoreApplication::translate("MainWindow", "Email:", nullptr));
        label_43->setText(QCoreApplication::translate("MainWindow", "Telefono contacto adicional:", nullptr));
        label_44->setText(QCoreApplication::translate("MainWindow", "Tipo de sangre:", nullptr));
        label_45->setText(QCoreApplication::translate("MainWindow", "Alegrias conocidas:", nullptr));
        label_46->setText(QCoreApplication::translate("MainWindow", "Enfermedades base:", nullptr));
        pushButton_34->setText(QCoreApplication::translate("MainWindow", "Crear ", nullptr));
        pushButton_35->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        CodigoNextExpedienteLabel->setText(QCoreApplication::translate("MainWindow", "00", nullptr));
        TipodeSangreCrear->setItemText(0, QString());
        TipodeSangreCrear->setItemText(1, QCoreApplication::translate("MainWindow", "A+", nullptr));
        TipodeSangreCrear->setItemText(2, QCoreApplication::translate("MainWindow", "A-", nullptr));
        TipodeSangreCrear->setItemText(3, QCoreApplication::translate("MainWindow", "B+", nullptr));
        TipodeSangreCrear->setItemText(4, QCoreApplication::translate("MainWindow", "B-", nullptr));
        TipodeSangreCrear->setItemText(5, QCoreApplication::translate("MainWindow", "AB+", nullptr));
        TipodeSangreCrear->setItemText(6, QCoreApplication::translate("MainWindow", "AB-", nullptr));
        TipodeSangreCrear->setItemText(7, QCoreApplication::translate("MainWindow", "O+", nullptr));
        TipodeSangreCrear->setItemText(8, QCoreApplication::translate("MainWindow", "O-", nullptr));

        label_14->setText(QCoreApplication::translate("MainWindow", "Encabezado:", nullptr));
        label_102->setText(QCoreApplication::translate("MainWindow", "Email de contacto adicional:", nullptr));
        label_48->setText(QCoreApplication::translate("MainWindow", "Agregar Datos al Expediente", nullptr));
        label_49->setText(QCoreApplication::translate("MainWindow", "Fecha:", nullptr));
        label_50->setText(QCoreApplication::translate("MainWindow", "Sintomas presentados:", nullptr));
        label_51->setText(QCoreApplication::translate("MainWindow", "Observaciones:", nullptr));
        label_52->setText(QCoreApplication::translate("MainWindow", "Recomendaciones:", nullptr));
        label_53->setText(QCoreApplication::translate("MainWindow", "Proxima cita recomendada:", nullptr));
        label_54->setText(QCoreApplication::translate("MainWindow", "Comentarios adicionales:", nullptr));
        pushButton_36->setText(QCoreApplication::translate("MainWindow", "Agregar", nullptr));
        pushButton_37->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_105->setText(QCoreApplication::translate("MainWindow", "Nombre del Paciente:", nullptr));
        label_106->setText(QCoreApplication::translate("MainWindow", "Identidad del Paciente:", nullptr));
        label_107->setText(QCoreApplication::translate("MainWindow", "Diagnositico:", nullptr));
        label_55->setText(QCoreApplication::translate("MainWindow", "Recetas", nullptr));
        pushButton_38->setText(QCoreApplication::translate("MainWindow", "Nueva Receta", nullptr));
        pushButton_39->setText(QCoreApplication::translate("MainWindow", "Buscar Receta", nullptr));
        pushButton_40->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_56->setText(QCoreApplication::translate("MainWindow", "Nueva Receta", nullptr));
        label_57->setText(QCoreApplication::translate("MainWindow", "Fecha:", nullptr));
        label_58->setText(QCoreApplication::translate("MainWindow", "Paciente:", nullptr));
        label_59->setText(QCoreApplication::translate("MainWindow", "Medicamento:", nullptr));
        medicamento_cb->setItemText(0, QCoreApplication::translate("MainWindow", "AMIODARONA", nullptr));
        medicamento_cb->setItemText(1, QCoreApplication::translate("MainWindow", "AMOXICILINA", nullptr));
        medicamento_cb->setItemText(2, QCoreApplication::translate("MainWindow", "BETAMETASONA", nullptr));
        medicamento_cb->setItemText(3, QCoreApplication::translate("MainWindow", "ETAMBUTOL", nullptr));
        medicamento_cb->setItemText(4, QCoreApplication::translate("MainWindow", "HIERRO", nullptr));
        medicamento_cb->setItemText(5, QCoreApplication::translate("MainWindow", "LOSARTAN", nullptr));
        medicamento_cb->setItemText(6, QCoreApplication::translate("MainWindow", "NORFLOXACINA", nullptr));
        medicamento_cb->setItemText(7, QCoreApplication::translate("MainWindow", "RIFAMPICINA ", nullptr));
        medicamento_cb->setItemText(8, QCoreApplication::translate("MainWindow", "POLIVITAM\303\215NICO", nullptr));
        medicamento_cb->setItemText(9, QCoreApplication::translate("MainWindow", "VITAMINA D", nullptr));

        lb_fecha_actual->setText(QString());
        pushButton_41->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        new_recipe->setText(QCoreApplication::translate("MainWindow", "Crear", nullptr));
        label_60->setText(QCoreApplication::translate("MainWindow", "Dosis:", nullptr));
        dosis_cb->setItemText(0, QCoreApplication::translate("MainWindow", "1 /kg al dia ", nullptr));
        dosis_cb->setItemText(1, QCoreApplication::translate("MainWindow", "2/kg al dia", nullptr));
        dosis_cb->setItemText(2, QCoreApplication::translate("MainWindow", "2 capsulas al dia", nullptr));
        dosis_cb->setItemText(3, QCoreApplication::translate("MainWindow", "4 capsulas al dia ", nullptr));
        dosis_cb->setItemText(4, QCoreApplication::translate("MainWindow", "2 capsulas cada 6 horas", nullptr));
        dosis_cb->setItemText(5, QCoreApplication::translate("MainWindow", "4 capsulas cada 6 horas", nullptr));
        dosis_cb->setItemText(6, QCoreApplication::translate("MainWindow", "2 capsulas cada 8 horas", nullptr));
        dosis_cb->setItemText(7, QCoreApplication::translate("MainWindow", "4 capsulas cada 8 horas", nullptr));
        dosis_cb->setItemText(8, QString());

        label_61->setText(QCoreApplication::translate("MainWindow", "Buscar Receta", nullptr));
        radioButton->setText(QCoreApplication::translate("MainWindow", "Paciente", nullptr));
        radioButton_2->setText(QCoreApplication::translate("MainWindow", "Fecha", nullptr));
        pushButton_43->setText(QCoreApplication::translate("MainWindow", "Buscar", nullptr));
        pushButton_44->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_62->setText(QCoreApplication::translate("MainWindow", "Receta", nullptr));
        label_63->setText(QCoreApplication::translate("MainWindow", "Reservaciones", nullptr));
        pushButton_45->setText(QCoreApplication::translate("MainWindow", "Nueva Reservaci\303\263n", nullptr));
        pushButton_46->setText(QCoreApplication::translate("MainWindow", "Modificar Reservaci\303\263n", nullptr));
        pushButton_47->setText(QCoreApplication::translate("MainWindow", "Eliminar Reservaci\303\263n", nullptr));
        pushButton_48->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_64->setText(QCoreApplication::translate("MainWindow", "Nueva Reservaci\303\263n", nullptr));
        label_65->setText(QCoreApplication::translate("MainWindow", "Sala:", nullptr));
        label_66->setText(QCoreApplication::translate("MainWindow", "Nombre del paciente:", nullptr));
        label_67->setText(QCoreApplication::translate("MainWindow", "Fecha:", nullptr));
        label_68->setText(QCoreApplication::translate("MainWindow", "Hora de Inicio:", nullptr));
        label_69->setText(QCoreApplication::translate("MainWindow", "Hora final:", nullptr));
        label_70->setText(QCoreApplication::translate("MainWindow", "Nombre del doctor:", nullptr));
        bt_reservar->setText(QCoreApplication::translate("MainWindow", "Reservar", nullptr));
        pushButton_50->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_108->setText(QCoreApplication::translate("MainWindow", "Observaciones:", nullptr));
        label_109->setText(QCoreApplication::translate("MainWindow", "Code:", nullptr));
        lbcodereservas->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        label_71->setText(QCoreApplication::translate("MainWindow", "Modificar Reservaci\303\263n", nullptr));
        label_72->setText(QCoreApplication::translate("MainWindow", "Nombre del paciente:", nullptr));
        label_73->setText(QCoreApplication::translate("MainWindow", "Fecha:", nullptr));
        label_74->setText(QCoreApplication::translate("MainWindow", "Hora de Inicio:", nullptr));
        label_75->setText(QCoreApplication::translate("MainWindow", "Hora final:", nullptr));
        label_76->setText(QCoreApplication::translate("MainWindow", "Nombre del doctor:", nullptr));
        btmodificarR->setText(QCoreApplication::translate("MainWindow", "Modificar", nullptr));
        pushButton_52->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_110->setText(QCoreApplication::translate("MainWindow", "Codigo:", nullptr));
        label_111->setText(QCoreApplication::translate("MainWindow", "Observaciones:", nullptr));
        bt_buscarMR->setText(QCoreApplication::translate("MainWindow", "Buscar", nullptr));
        label_77->setText(QCoreApplication::translate("MainWindow", "Eliminar Reservaci\303\263n", nullptr));
        label_78->setText(QCoreApplication::translate("MainWindow", "Reservaciones:", nullptr));
        bt_EliminarR->setText(QCoreApplication::translate("MainWindow", "Eliminar", nullptr));
        pushButton_54->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_112->setText(QCoreApplication::translate("MainWindow", "Codigo:", nullptr));
        label_79->setText(QCoreApplication::translate("MainWindow", "Agenda de Consultas", nullptr));
        pushButton_55->setText(QCoreApplication::translate("MainWindow", "Nueva Cita", nullptr));
        pushButton_56->setText(QCoreApplication::translate("MainWindow", "Modificar Cita", nullptr));
        pushButton_57->setText(QCoreApplication::translate("MainWindow", "Eliminar Cita", nullptr));
        pushButton_58->setText(QCoreApplication::translate("MainWindow", "Consulta de Citas", nullptr));
        pushButton_59->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_80->setText(QCoreApplication::translate("MainWindow", "Nueva Cita", nullptr));
        label_81->setText(QCoreApplication::translate("MainWindow", "Nombre:", nullptr));
        label_82->setText(QCoreApplication::translate("MainWindow", "Fecha:", nullptr));
        label_83->setText(QCoreApplication::translate("MainWindow", "Hora:", nullptr));
        btNewCita->setText(QCoreApplication::translate("MainWindow", "Crear", nullptr));
        pushButton_61->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_84->setText(QCoreApplication::translate("MainWindow", "Modificar Cita", nullptr));
        label_85->setText(QCoreApplication::translate("MainWindow", "Cita:", nullptr));
        label_86->setText(QCoreApplication::translate("MainWindow", "Hora:", nullptr));
        label_87->setText(QCoreApplication::translate("MainWindow", "Fecha:", nullptr));
        pushButton_62->setText(QCoreApplication::translate("MainWindow", "Modificar", nullptr));
        pushButton_63->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_88->setText(QCoreApplication::translate("MainWindow", "Eliminar Cita", nullptr));
        label_89->setText(QCoreApplication::translate("MainWindow", "Cita:", nullptr));
        pushButton_64->setText(QCoreApplication::translate("MainWindow", "Eliminar", nullptr));
        pushButton_65->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_90->setText(QCoreApplication::translate("MainWindow", "Consultar Cita", nullptr));
        label_91->setText(QCoreApplication::translate("MainWindow", "Fecha:", nullptr));
        pushButton_66->setText(QCoreApplication::translate("MainWindow", "Consultar", nullptr));
        pushButton_67->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_92->setText(QCoreApplication::translate("MainWindow", "Opciones de usuario", nullptr));
        pushButton_68->setText(QCoreApplication::translate("MainWindow", "Cambiar Contrase\303\261a", nullptr));
        pushButton_69->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_93->setText(QCoreApplication::translate("MainWindow", "Cambiar Contrase\303\261a", nullptr));
        label_94->setText(QCoreApplication::translate("MainWindow", "Contrase\303\261a Actual:", nullptr));
        label_95->setText(QString());
        label_96->setText(QCoreApplication::translate("MainWindow", "Nueva Contrase\303\261a:", nullptr));
        pushButton_70->setText(QCoreApplication::translate("MainWindow", "Cambiar", nullptr));
        pushButton_71->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_47->setText(QCoreApplication::translate("MainWindow", "*Si nunca a entrado a esta opcion su password es \"admin\"", nullptr));
        label_97->setText(QCoreApplication::translate("MainWindow", "Reportes", nullptr));
        pushButton_72->setText(QCoreApplication::translate("MainWindow", "Pacientes", nullptr));
        pushButton_73->setText(QCoreApplication::translate("MainWindow", "Citas", nullptr));
        pushButton_78->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_98->setText(QCoreApplication::translate("MainWindow", "Pacientes", nullptr));
        label_99->setText(QCoreApplication::translate("MainWindow", "Fecha:", nullptr));
        pushButton_74->setText(QCoreApplication::translate("MainWindow", "Ver", nullptr));
        pushButton_75->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_100->setText(QCoreApplication::translate("MainWindow", "Citas", nullptr));
        label_101->setText(QCoreApplication::translate("MainWindow", "Fecha:", nullptr));
        pushButton_76->setText(QCoreApplication::translate("MainWindow", "Ver", nullptr));
        pushButton_77->setText(QCoreApplication::translate("MainWindow", "Regresar", nullptr));
        label_103->setText(QCoreApplication::translate("MainWindow", "Agregar rol", nullptr));
        label_104->setText(QCoreApplication::translate("MainWindow", "Ingrese el nuevo rol:", nullptr));
        pushButton_80->setText(QCoreApplication::translate("MainWindow", "Agregar", nullptr));
        checkBox->setText(QCoreApplication::translate("MainWindow", "CheckBox", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
